/**
 * This class is generated by jOOQ
 */
package com.lrest.server.jooqmodel.tables;


import com.lrest.server.jooqmodel.Gouchehui2_0;
import com.lrest.server.jooqmodel.Keys;
import com.lrest.server.jooqmodel.tables.records.GchPayAreaLowPriceRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 订单中区域最低价表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GchPayAreaLowPrice extends TableImpl<GchPayAreaLowPriceRecord> {

    private static final long serialVersionUID = 1953769995;

    /**
     * The reference instance of <code>gouchehui2.0.gch_pay_area_low_price</code>
     */
    public static final GchPayAreaLowPrice GCH_PAY_AREA_LOW_PRICE = new GchPayAreaLowPrice();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GchPayAreaLowPriceRecord> getRecordType() {
        return GchPayAreaLowPriceRecord.class;
    }

    /**
     * The column <code>gouchehui2.0.gch_pay_area_low_price.id</code>. 主键
     */
    public final TableField<GchPayAreaLowPriceRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "主键");

    /**
     * The column <code>gouchehui2.0.gch_pay_area_low_price.pay_id</code>. 支付订单id
     */
    public final TableField<GchPayAreaLowPriceRecord, String> PAY_ID = createField("pay_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "支付订单id");

    /**
     * The column <code>gouchehui2.0.gch_pay_area_low_price.car_price_id</code>. 报价id
     */
    public final TableField<GchPayAreaLowPriceRecord, String> CAR_PRICE_ID = createField("car_price_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "报价id");

    /**
     * The column <code>gouchehui2.0.gch_pay_area_low_price.id_4s</code>.
     */
    public final TableField<GchPayAreaLowPriceRecord, String> ID_4S = createField("id_4s", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

    /**
     * The column <code>gouchehui2.0.gch_pay_area_low_price.pay_low_price</code>. 支付的最低价
     */
    public final TableField<GchPayAreaLowPriceRecord, Integer> PAY_LOW_PRICE = createField("pay_low_price", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "支付的最低价");

    /**
     * The column <code>gouchehui2.0.gch_pay_area_low_price.area_name</code>. 区域名称
     */
    public final TableField<GchPayAreaLowPriceRecord, String> AREA_NAME = createField("area_name", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "区域名称");

    /**
     * The column <code>gouchehui2.0.gch_pay_area_low_price.sales_area_level</code>. 销售区域权重
     */
    public final TableField<GchPayAreaLowPriceRecord, Integer> SALES_AREA_LEVEL = createField("sales_area_level", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "销售区域权重");

    /**
     * The column <code>gouchehui2.0.gch_pay_area_low_price.pay_obj</code>. 支付对象（1：询价 2：定金）
     */
    public final TableField<GchPayAreaLowPriceRecord, Byte> PAY_OBJ = createField("pay_obj", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "支付对象（1：询价 2：定金）");

    /**
     * The column <code>gouchehui2.0.gch_pay_area_low_price.createtime</code>. 创建时间
     */
    public final TableField<GchPayAreaLowPriceRecord, Timestamp> CREATETIME = createField("createtime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");

    /**
     * The column <code>gouchehui2.0.gch_pay_area_low_price.createuser</code>. 创建人
     */
    public final TableField<GchPayAreaLowPriceRecord, String> CREATEUSER = createField("createuser", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "创建人");

    /**
     * The column <code>gouchehui2.0.gch_pay_area_low_price.isdelete</code>. 是否删除
     */
    public final TableField<GchPayAreaLowPriceRecord, Integer> ISDELETE = createField("isdelete", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "是否删除");

    /**
     * The column <code>gouchehui2.0.gch_pay_area_low_price.updatetime</code>. 修改时间
     */
    public final TableField<GchPayAreaLowPriceRecord, Timestamp> UPDATETIME = createField("updatetime", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.inline("0000-00-00 00:00:00", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "修改时间");

    /**
     * The column <code>gouchehui2.0.gch_pay_area_low_price.updateuser</code>. 修改人
     */
    public final TableField<GchPayAreaLowPriceRecord, String> UPDATEUSER = createField("updateuser", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "修改人");

    /**
     * The column <code>gouchehui2.0.gch_pay_area_low_price.card_place</code>. 上牌地(如果不填代表获取此底价车全部上牌地)
     */
    public final TableField<GchPayAreaLowPriceRecord, String> CARD_PLACE = createField("card_place", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "上牌地(如果不填代表获取此底价车全部上牌地)");

    /**
     * Create a <code>gouchehui2.0.gch_pay_area_low_price</code> table reference
     */
    public GchPayAreaLowPrice() {
        this("gch_pay_area_low_price", null);
    }

    /**
     * Create an aliased <code>gouchehui2.0.gch_pay_area_low_price</code> table reference
     */
    public GchPayAreaLowPrice(String alias) {
        this(alias, GCH_PAY_AREA_LOW_PRICE);
    }

    private GchPayAreaLowPrice(String alias, Table<GchPayAreaLowPriceRecord> aliased) {
        this(alias, aliased, null);
    }

    private GchPayAreaLowPrice(String alias, Table<GchPayAreaLowPriceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "订单中区域最低价表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Gouchehui2_0.GOUCHEHUI2_0;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GchPayAreaLowPriceRecord> getPrimaryKey() {
        return Keys.KEY_GCH_PAY_AREA_LOW_PRICE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GchPayAreaLowPriceRecord>> getKeys() {
        return Arrays.<UniqueKey<GchPayAreaLowPriceRecord>>asList(Keys.KEY_GCH_PAY_AREA_LOW_PRICE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchPayAreaLowPrice as(String alias) {
        return new GchPayAreaLowPrice(alias, this);
    }

    /**
     * Rename this table
     */
    public GchPayAreaLowPrice rename(String name) {
        return new GchPayAreaLowPrice(name, null);
    }
}
