/**
 * This class is generated by jOOQ
 */
package com.lrest.server.jooqmodel.tables;


import com.lrest.server.jooqmodel.Gouchehui2_0;
import com.lrest.server.jooqmodel.Keys;
import com.lrest.server.jooqmodel.tables.records.GchWxpayPackageRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GchWxpayPackage extends TableImpl<GchWxpayPackageRecord> {

    private static final long serialVersionUID = -269264568;

    /**
     * The reference instance of <code>gouchehui2.0.gch_wxpay_package</code>
     */
    public static final GchWxpayPackage GCH_WXPAY_PACKAGE = new GchWxpayPackage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GchWxpayPackageRecord> getRecordType() {
        return GchWxpayPackageRecord.class;
    }

    /**
     * The column <code>gouchehui2.0.gch_wxpay_package.id</code>. 主键ID
     */
    public final TableField<GchWxpayPackageRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "主键ID");

    /**
     * The column <code>gouchehui2.0.gch_wxpay_package.pay_id</code>.
     */
    public final TableField<GchWxpayPackageRecord, String> PAY_ID = createField("pay_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

    /**
     * The column <code>gouchehui2.0.gch_wxpay_package.out_trade_no</code>. 本系统的订单号
     */
    public final TableField<GchWxpayPackageRecord, String> OUT_TRADE_NO = createField("out_trade_no", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "本系统的订单号");

    /**
     * The column <code>gouchehui2.0.gch_wxpay_package.transaction_id</code>. 微信支付订单号
     */
    public final TableField<GchWxpayPackageRecord, String> TRANSACTION_ID = createField("transaction_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "微信支付订单号");

    /**
     * The column <code>gouchehui2.0.gch_wxpay_package.total_fee</code>. 订单总金额(单位为分)
     */
    public final TableField<GchWxpayPackageRecord, Integer> TOTAL_FEE = createField("total_fee", org.jooq.impl.SQLDataType.INTEGER, this, "订单总金额(单位为分)");

    /**
     * The column <code>gouchehui2.0.gch_wxpay_package.trade_type</code>. 交易类型
     */
    public final TableField<GchWxpayPackageRecord, String> TRADE_TYPE = createField("trade_type", org.jooq.impl.SQLDataType.VARCHAR.length(16), this, "交易类型");

    /**
     * The column <code>gouchehui2.0.gch_wxpay_package.bank_type</code>. 付款银行
     */
    public final TableField<GchWxpayPackageRecord, String> BANK_TYPE = createField("bank_type", org.jooq.impl.SQLDataType.VARCHAR.length(16), this, "付款银行");

    /**
     * The column <code>gouchehui2.0.gch_wxpay_package.time_end</code>.
     */
    public final TableField<GchWxpayPackageRecord, String> TIME_END = createField("time_end", org.jooq.impl.SQLDataType.VARCHAR.length(14), this, "");

    /**
     * The column <code>gouchehui2.0.gch_wxpay_package.package</code>. 整个返回包
     */
    public final TableField<GchWxpayPackageRecord, String> PACKAGE = createField("package", org.jooq.impl.SQLDataType.CLOB, this, "整个返回包");

    /**
     * Create a <code>gouchehui2.0.gch_wxpay_package</code> table reference
     */
    public GchWxpayPackage() {
        this("gch_wxpay_package", null);
    }

    /**
     * Create an aliased <code>gouchehui2.0.gch_wxpay_package</code> table reference
     */
    public GchWxpayPackage(String alias) {
        this(alias, GCH_WXPAY_PACKAGE);
    }

    private GchWxpayPackage(String alias, Table<GchWxpayPackageRecord> aliased) {
        this(alias, aliased, null);
    }

    private GchWxpayPackage(String alias, Table<GchWxpayPackageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Gouchehui2_0.GOUCHEHUI2_0;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<GchWxpayPackageRecord, Integer> getIdentity() {
        return Keys.IDENTITY_GCH_WXPAY_PACKAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GchWxpayPackageRecord> getPrimaryKey() {
        return Keys.KEY_GCH_WXPAY_PACKAGE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GchWxpayPackageRecord>> getKeys() {
        return Arrays.<UniqueKey<GchWxpayPackageRecord>>asList(Keys.KEY_GCH_WXPAY_PACKAGE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchWxpayPackage as(String alias) {
        return new GchWxpayPackage(alias, this);
    }

    /**
     * Rename this table
     */
    public GchWxpayPackage rename(String name) {
        return new GchWxpayPackage(name, null);
    }
}
