/**
 * This class is generated by jOOQ
 */
package com.lrest.server.jooqmodel.tables.records;


import com.lrest.server.jooqmodel.tables.GchArea;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 4S所在区域
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GchAreaRecord extends UpdatableRecordImpl<GchAreaRecord> implements Record7<String, String, Timestamp, String, Integer, Timestamp, String> {

    private static final long serialVersionUID = 2010906522;

    /**
     * Setter for <code>gouchehui2.0.gch_area.id</code>. 主键
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_area.id</code>. 主键
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_area.area_name</code>. 区域名称
     */
    public void setAreaName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_area.area_name</code>. 区域名称
     */
    public String getAreaName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_area.createtime</code>. 创建时间
     */
    public void setCreatetime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_area.createtime</code>. 创建时间
     */
    public Timestamp getCreatetime() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_area.createuser</code>. 创建人
     */
    public void setCreateuser(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_area.createuser</code>. 创建人
     */
    public String getCreateuser() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_area.isdelete</code>. 是否删除
     */
    public void setIsdelete(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_area.isdelete</code>. 是否删除
     */
    public Integer getIsdelete() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_area.updatetime</code>. 修改时间
     */
    public void setUpdatetime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_area.updatetime</code>. 修改时间
     */
    public Timestamp getUpdatetime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_area.updateuser</code>. 修改人
     */
    public void setUpdateuser(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_area.updateuser</code>. 修改人
     */
    public String getUpdateuser() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, Timestamp, String, Integer, Timestamp, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, Timestamp, String, Integer, Timestamp, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return GchArea.GCH_AREA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return GchArea.GCH_AREA.AREA_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return GchArea.GCH_AREA.CREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return GchArea.GCH_AREA.CREATEUSER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return GchArea.GCH_AREA.ISDELETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return GchArea.GCH_AREA.UPDATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return GchArea.GCH_AREA.UPDATEUSER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAreaName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCreateuser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getIsdelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getUpdateuser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchAreaRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchAreaRecord value2(String value) {
        setAreaName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchAreaRecord value3(Timestamp value) {
        setCreatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchAreaRecord value4(String value) {
        setCreateuser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchAreaRecord value5(Integer value) {
        setIsdelete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchAreaRecord value6(Timestamp value) {
        setUpdatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchAreaRecord value7(String value) {
        setUpdateuser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchAreaRecord values(String value1, String value2, Timestamp value3, String value4, Integer value5, Timestamp value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GchAreaRecord
     */
    public GchAreaRecord() {
        super(GchArea.GCH_AREA);
    }

    /**
     * Create a detached, initialised GchAreaRecord
     */
    public GchAreaRecord(String id, String areaName, Timestamp createtime, String createuser, Integer isdelete, Timestamp updatetime, String updateuser) {
        super(GchArea.GCH_AREA);

        set(0, id);
        set(1, areaName);
        set(2, createtime);
        set(3, createuser);
        set(4, isdelete);
        set(5, updatetime);
        set(6, updateuser);
    }
}
