/**
 * This class is generated by jOOQ
 */
package com.lrest.server.jooqmodel.tables.records;


import com.lrest.server.jooqmodel.tables.GchCarModelPrefer;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 4s用户车型喜好表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GchCarModelPreferRecord extends UpdatableRecordImpl<GchCarModelPreferRecord> implements Record10<String, String, String, String, String, Timestamp, String, Integer, Timestamp, String> {

    private static final long serialVersionUID = -1697630366;

    /**
     * Setter for <code>gouchehui2.0.gch_car_model_prefer.id</code>. 主键
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_model_prefer.id</code>. 主键
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_model_prefer.brand_id</code>. 所属品牌
     */
    public void setBrandId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_model_prefer.brand_id</code>. 所属品牌
     */
    public String getBrandId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_model_prefer.car_model_id</code>. 车型ID
     */
    public void setCarModelId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_model_prefer.car_model_id</code>. 车型ID
     */
    public String getCarModelId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_model_prefer.user_id</code>. 访问量
     */
    public void setUserId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_model_prefer.user_id</code>. 访问量
     */
    public String getUserId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_model_prefer.car_model_name</code>. 名称
     */
    public void setCarModelName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_model_prefer.car_model_name</code>. 名称
     */
    public String getCarModelName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_model_prefer.createtime</code>. 创建时间
     */
    public void setCreatetime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_model_prefer.createtime</code>. 创建时间
     */
    public Timestamp getCreatetime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_model_prefer.createuser</code>. 创建人
     */
    public void setCreateuser(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_model_prefer.createuser</code>. 创建人
     */
    public String getCreateuser() {
        return (String) get(6);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_model_prefer.isdelete</code>. 是否删除
     */
    public void setIsdelete(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_model_prefer.isdelete</code>. 是否删除
     */
    public Integer getIsdelete() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_model_prefer.updatetime</code>. 修改时间
     */
    public void setUpdatetime(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_model_prefer.updatetime</code>. 修改时间
     */
    public Timestamp getUpdatetime() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_model_prefer.updateuser</code>. 修改人
     */
    public void setUpdateuser(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_model_prefer.updateuser</code>. 修改人
     */
    public String getUpdateuser() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, String, String, Timestamp, String, Integer, Timestamp, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, String, String, Timestamp, String, Integer, Timestamp, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return GchCarModelPrefer.GCH_CAR_MODEL_PREFER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return GchCarModelPrefer.GCH_CAR_MODEL_PREFER.BRAND_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return GchCarModelPrefer.GCH_CAR_MODEL_PREFER.CAR_MODEL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return GchCarModelPrefer.GCH_CAR_MODEL_PREFER.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return GchCarModelPrefer.GCH_CAR_MODEL_PREFER.CAR_MODEL_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return GchCarModelPrefer.GCH_CAR_MODEL_PREFER.CREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return GchCarModelPrefer.GCH_CAR_MODEL_PREFER.CREATEUSER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return GchCarModelPrefer.GCH_CAR_MODEL_PREFER.ISDELETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return GchCarModelPrefer.GCH_CAR_MODEL_PREFER.UPDATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return GchCarModelPrefer.GCH_CAR_MODEL_PREFER.UPDATEUSER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getBrandId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCarModelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCarModelName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCreateuser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getIsdelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getUpdatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getUpdateuser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarModelPreferRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarModelPreferRecord value2(String value) {
        setBrandId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarModelPreferRecord value3(String value) {
        setCarModelId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarModelPreferRecord value4(String value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarModelPreferRecord value5(String value) {
        setCarModelName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarModelPreferRecord value6(Timestamp value) {
        setCreatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarModelPreferRecord value7(String value) {
        setCreateuser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarModelPreferRecord value8(Integer value) {
        setIsdelete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarModelPreferRecord value9(Timestamp value) {
        setUpdatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarModelPreferRecord value10(String value) {
        setUpdateuser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarModelPreferRecord values(String value1, String value2, String value3, String value4, String value5, Timestamp value6, String value7, Integer value8, Timestamp value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GchCarModelPreferRecord
     */
    public GchCarModelPreferRecord() {
        super(GchCarModelPrefer.GCH_CAR_MODEL_PREFER);
    }

    /**
     * Create a detached, initialised GchCarModelPreferRecord
     */
    public GchCarModelPreferRecord(String id, String brandId, String carModelId, String userId, String carModelName, Timestamp createtime, String createuser, Integer isdelete, Timestamp updatetime, String updateuser) {
        super(GchCarModelPrefer.GCH_CAR_MODEL_PREFER);

        set(0, id);
        set(1, brandId);
        set(2, carModelId);
        set(3, userId);
        set(4, carModelName);
        set(5, createtime);
        set(6, createuser);
        set(7, isdelete);
        set(8, updatetime);
        set(9, updateuser);
    }
}
