/**
 * This class is generated by jOOQ
 */
package com.lrest.server.jooqmodel.tables.records;


import com.lrest.server.jooqmodel.tables.GchCoin;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 积分详情表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GchCoinRecord extends UpdatableRecordImpl<GchCoinRecord> implements Record13<String, String, Byte, Integer, String, Integer, String, Timestamp, String, Integer, Timestamp, String, String> {

    private static final long serialVersionUID = 1443315757;

    /**
     * Setter for <code>gouchehui2.0.gch_coin.id</code>. id
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_coin.id</code>. id
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_coin.user_id</code>. 关联user的id
     */
    public void setUserId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_coin.user_id</code>. 关联user的id
     */
    public String getUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_coin.role</code>. 角色
     */
    public void setRole(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_coin.role</code>. 角色
     */
    public Byte getRole() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_coin.coin</code>. 车币
     */
    public void setCoin(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_coin.coin</code>. 车币
     */
    public Integer getCoin() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_coin.info</code>. 积分增减说明
     */
    public void setInfo(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_coin.info</code>. 积分增减说明
     */
    public String getInfo() {
        return (String) get(4);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_coin.flag</code>. 来源标志
     */
    public void setFlag(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_coin.flag</code>. 来源标志
     */
    public Integer getFlag() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_coin.from_id</code>. 来源ID
     */
    public void setFromId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_coin.from_id</code>. 来源ID
     */
    public String getFromId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_coin.createtime</code>. 创建时间
     */
    public void setCreatetime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_coin.createtime</code>. 创建时间
     */
    public Timestamp getCreatetime() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_coin.createuser</code>. 创建人
     */
    public void setCreateuser(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_coin.createuser</code>. 创建人
     */
    public String getCreateuser() {
        return (String) get(8);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_coin.isdelete</code>. 是否删除
     */
    public void setIsdelete(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_coin.isdelete</code>. 是否删除
     */
    public Integer getIsdelete() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_coin.updatetime</code>. 修改时间
     */
    public void setUpdatetime(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_coin.updatetime</code>. 修改时间
     */
    public Timestamp getUpdatetime() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_coin.updateuser</code>. 修改人
     */
    public void setUpdateuser(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_coin.updateuser</code>. 修改人
     */
    public String getUpdateuser() {
        return (String) get(11);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_coin.types</code>. 区分类别
     */
    public void setTypes(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_coin.types</code>. 区分类别
     */
    public String getTypes() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<String, String, Byte, Integer, String, Integer, String, Timestamp, String, Integer, Timestamp, String, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<String, String, Byte, Integer, String, Integer, String, Timestamp, String, Integer, Timestamp, String, String> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return GchCoin.GCH_COIN.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return GchCoin.GCH_COIN.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return GchCoin.GCH_COIN.ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return GchCoin.GCH_COIN.COIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return GchCoin.GCH_COIN.INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return GchCoin.GCH_COIN.FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return GchCoin.GCH_COIN.FROM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return GchCoin.GCH_COIN.CREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return GchCoin.GCH_COIN.CREATEUSER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return GchCoin.GCH_COIN.ISDELETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return GchCoin.GCH_COIN.UPDATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return GchCoin.GCH_COIN.UPDATEUSER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return GchCoin.GCH_COIN.TYPES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCoin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getFromId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCreateuser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getIsdelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getUpdatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getUpdateuser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getTypes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCoinRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCoinRecord value2(String value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCoinRecord value3(Byte value) {
        setRole(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCoinRecord value4(Integer value) {
        setCoin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCoinRecord value5(String value) {
        setInfo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCoinRecord value6(Integer value) {
        setFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCoinRecord value7(String value) {
        setFromId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCoinRecord value8(Timestamp value) {
        setCreatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCoinRecord value9(String value) {
        setCreateuser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCoinRecord value10(Integer value) {
        setIsdelete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCoinRecord value11(Timestamp value) {
        setUpdatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCoinRecord value12(String value) {
        setUpdateuser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCoinRecord value13(String value) {
        setTypes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCoinRecord values(String value1, String value2, Byte value3, Integer value4, String value5, Integer value6, String value7, Timestamp value8, String value9, Integer value10, Timestamp value11, String value12, String value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GchCoinRecord
     */
    public GchCoinRecord() {
        super(GchCoin.GCH_COIN);
    }

    /**
     * Create a detached, initialised GchCoinRecord
     */
    public GchCoinRecord(String id, String userId, Byte role, Integer coin, String info, Integer flag, String fromId, Timestamp createtime, String createuser, Integer isdelete, Timestamp updatetime, String updateuser, String types) {
        super(GchCoin.GCH_COIN);

        set(0, id);
        set(1, userId);
        set(2, role);
        set(3, coin);
        set(4, info);
        set(5, flag);
        set(6, fromId);
        set(7, createtime);
        set(8, createuser);
        set(9, isdelete);
        set(10, updatetime);
        set(11, updateuser);
        set(12, types);
    }
}
