/**
 * This class is generated by jOOQ
 */
package com.lrest.server.jooqmodel.tables.records;


import com.lrest.server.jooqmodel.tables.GchCity;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 4S店所在城市
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GchCityRecord extends UpdatableRecordImpl<GchCityRecord> implements Record9<String, String, String, Timestamp, String, Integer, Timestamp, String, Byte> {

    private static final long serialVersionUID = -1144593214;

    /**
     * Setter for <code>gouchehui2.0.gch_city.id</code>. 主键
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_city.id</code>. 主键
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_city.province_id</code>. 所属省份
     */
    public void setProvinceId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_city.province_id</code>. 所属省份
     */
    public String getProvinceId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_city.city_name</code>. 城市名称
     */
    public void setCityName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_city.city_name</code>. 城市名称
     */
    public String getCityName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_city.createtime</code>. 创建时间
     */
    public void setCreatetime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_city.createtime</code>. 创建时间
     */
    public Timestamp getCreatetime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_city.createuser</code>. 创建人
     */
    public void setCreateuser(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_city.createuser</code>. 创建人
     */
    public String getCreateuser() {
        return (String) get(4);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_city.isdelete</code>. 是否删除
     */
    public void setIsdelete(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_city.isdelete</code>. 是否删除
     */
    public Integer getIsdelete() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_city.updatetime</code>. 修改时间
     */
    public void setUpdatetime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_city.updatetime</code>. 修改时间
     */
    public Timestamp getUpdatetime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_city.updateuser</code>. 修改人
     */
    public void setUpdateuser(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_city.updateuser</code>. 修改人
     */
    public String getUpdateuser() {
        return (String) get(7);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_city.status</code>. 是否启用 1启用 0不启用
     */
    public void setStatus(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_city.status</code>. 是否启用 1启用 0不启用
     */
    public Byte getStatus() {
        return (Byte) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, Timestamp, String, Integer, Timestamp, String, Byte> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, Timestamp, String, Integer, Timestamp, String, Byte> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return GchCity.GCH_CITY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return GchCity.GCH_CITY.PROVINCE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return GchCity.GCH_CITY.CITY_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return GchCity.GCH_CITY.CREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return GchCity.GCH_CITY.CREATEUSER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return GchCity.GCH_CITY.ISDELETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return GchCity.GCH_CITY.UPDATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return GchCity.GCH_CITY.UPDATEUSER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field9() {
        return GchCity.GCH_CITY.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getProvinceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCityName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCreateuser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getIsdelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getUpdatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getUpdateuser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value9() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCityRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCityRecord value2(String value) {
        setProvinceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCityRecord value3(String value) {
        setCityName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCityRecord value4(Timestamp value) {
        setCreatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCityRecord value5(String value) {
        setCreateuser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCityRecord value6(Integer value) {
        setIsdelete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCityRecord value7(Timestamp value) {
        setUpdatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCityRecord value8(String value) {
        setUpdateuser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCityRecord value9(Byte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCityRecord values(String value1, String value2, String value3, Timestamp value4, String value5, Integer value6, Timestamp value7, String value8, Byte value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GchCityRecord
     */
    public GchCityRecord() {
        super(GchCity.GCH_CITY);
    }

    /**
     * Create a detached, initialised GchCityRecord
     */
    public GchCityRecord(String id, String provinceId, String cityName, Timestamp createtime, String createuser, Integer isdelete, Timestamp updatetime, String updateuser, Byte status) {
        super(GchCity.GCH_CITY);

        set(0, id);
        set(1, provinceId);
        set(2, cityName);
        set(3, createtime);
        set(4, createuser);
        set(5, isdelete);
        set(6, updatetime);
        set(7, updateuser);
        set(8, status);
    }
}
