/**
 * This class is generated by jOOQ
 */
package com.lrest.server.jooqmodel.tables.records;


import com.lrest.server.jooqmodel.tables.GchCarPrefer;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 车款表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GchCarPreferRecord extends UpdatableRecordImpl<GchCarPreferRecord> implements Record8<String, String, String, String, String, Timestamp, String, Integer> {

    private static final long serialVersionUID = -1283218801;

    /**
     * Setter for <code>gouchehui2.0.gch_car_prefer.id</code>. 主键
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_prefer.id</code>. 主键
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_prefer.car_id</code>. 访问量
     */
    public void setCarId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_prefer.car_id</code>. 访问量
     */
    public String getCarId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_prefer.car_model_id</code>. 所属车型
     */
    public void setCarModelId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_prefer.car_model_id</code>. 所属车型
     */
    public String getCarModelId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_prefer.car_name</code>. 名称
     */
    public void setCarName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_prefer.car_name</code>. 名称
     */
    public String getCarName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_prefer.user_id</code>. 描述
     */
    public void setUserId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_prefer.user_id</code>. 描述
     */
    public String getUserId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_prefer.createtime</code>. 创建时间
     */
    public void setCreatetime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_prefer.createtime</code>. 创建时间
     */
    public Timestamp getCreatetime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_prefer.createuser</code>. 创建人
     */
    public void setCreateuser(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_prefer.createuser</code>. 创建人
     */
    public String getCreateuser() {
        return (String) get(6);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_prefer.isdelete</code>. 是否删除
     */
    public void setIsdelete(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_prefer.isdelete</code>. 是否删除
     */
    public Integer getIsdelete() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, String, String, String, Timestamp, String, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, String, String, String, Timestamp, String, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return GchCarPrefer.GCH_CAR_PREFER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return GchCarPrefer.GCH_CAR_PREFER.CAR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return GchCarPrefer.GCH_CAR_PREFER.CAR_MODEL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return GchCarPrefer.GCH_CAR_PREFER.CAR_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return GchCarPrefer.GCH_CAR_PREFER.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return GchCarPrefer.GCH_CAR_PREFER.CREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return GchCarPrefer.GCH_CAR_PREFER.CREATEUSER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return GchCarPrefer.GCH_CAR_PREFER.ISDELETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCarId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCarModelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCarName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCreateuser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getIsdelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarPreferRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarPreferRecord value2(String value) {
        setCarId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarPreferRecord value3(String value) {
        setCarModelId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarPreferRecord value4(String value) {
        setCarName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarPreferRecord value5(String value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarPreferRecord value6(Timestamp value) {
        setCreatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarPreferRecord value7(String value) {
        setCreateuser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarPreferRecord value8(Integer value) {
        setIsdelete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarPreferRecord values(String value1, String value2, String value3, String value4, String value5, Timestamp value6, String value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GchCarPreferRecord
     */
    public GchCarPreferRecord() {
        super(GchCarPrefer.GCH_CAR_PREFER);
    }

    /**
     * Create a detached, initialised GchCarPreferRecord
     */
    public GchCarPreferRecord(String id, String carId, String carModelId, String carName, String userId, Timestamp createtime, String createuser, Integer isdelete) {
        super(GchCarPrefer.GCH_CAR_PREFER);

        set(0, id);
        set(1, carId);
        set(2, carModelId);
        set(3, carName);
        set(4, userId);
        set(5, createtime);
        set(6, createuser);
        set(7, isdelete);
    }
}
