/**
 * This class is generated by jOOQ
 */
package com.lrest.server.jooqmodel.tables.records;


import com.lrest.server.jooqmodel.tables.GchCar;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 车款表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GchCarRecord extends UpdatableRecordImpl<GchCarRecord> implements Record17<String, String, Integer, String, String, String, Timestamp, String, Integer, Timestamp, String, String, Integer, Integer, Integer, Byte, String> {

    private static final long serialVersionUID = 1053566110;

    /**
     * Setter for <code>gouchehui2.0.gch_car.id</code>. 主键
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car.id</code>. 主键
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car.car_model_id</code>. 所属车型
     */
    public void setCarModelId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car.car_model_id</code>. 所属车型
     */
    public String getCarModelId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car.access_quantity</code>. 访问量
     */
    public void setAccessQuantity(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car.access_quantity</code>. 访问量
     */
    public Integer getAccessQuantity() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car.car_name</code>. 名称
     */
    public void setCarName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car.car_name</code>. 名称
     */
    public String getCarName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car.imgurl</code>. 图片
     */
    public void setImgurl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car.imgurl</code>. 图片
     */
    public String getImgurl() {
        return (String) get(4);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car.description</code>. 描述
     */
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car.description</code>. 描述
     */
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car.createtime</code>. 创建时间
     */
    public void setCreatetime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car.createtime</code>. 创建时间
     */
    public Timestamp getCreatetime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car.createuser</code>. 创建人
     */
    public void setCreateuser(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car.createuser</code>. 创建人
     */
    public String getCreateuser() {
        return (String) get(7);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car.isdelete</code>. 是否删除
     */
    public void setIsdelete(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car.isdelete</code>. 是否删除
     */
    public Integer getIsdelete() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car.updatetime</code>. 修改时间
     */
    public void setUpdatetime(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car.updatetime</code>. 修改时间
     */
    public Timestamp getUpdatetime() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car.updateuser</code>. 修改人
     */
    public void setUpdateuser(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car.updateuser</code>. 修改人
     */
    public String getUpdateuser() {
        return (String) get(10);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car.alif</code>.
     */
    public void setAlif(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car.alif</code>.
     */
    public String getAlif() {
        return (String) get(11);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car.xj_count</code>. 询价总数
     */
    public void setXjCount(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car.xj_count</code>. 询价总数
     */
    public Integer getXjCount() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car.auth_price</code>. 官方指导价
     */
    public void setAuthPrice(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car.auth_price</code>. 官方指导价
     */
    public Integer getAuthPrice() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car.order</code>.
     */
    public void setOrder(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car.order</code>.
     */
    public Integer getOrder() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car.status</code>. 车款状态 1：在售；0：停售。
     */
    public void setStatus(Byte value) {
        set(15, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car.status</code>. 车款状态 1：在售；0：停售。
     */
    public Byte getStatus() {
        return (Byte) get(15);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car.displacement</code>. 排量
     */
    public void setDisplacement(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car.displacement</code>. 排量
     */
    public String getDisplacement() {
        return (String) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<String, String, Integer, String, String, String, Timestamp, String, Integer, Timestamp, String, String, Integer, Integer, Integer, Byte, String> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<String, String, Integer, String, String, String, Timestamp, String, Integer, Timestamp, String, String, Integer, Integer, Integer, Byte, String> valuesRow() {
        return (Row17) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return GchCar.GCH_CAR.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return GchCar.GCH_CAR.CAR_MODEL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return GchCar.GCH_CAR.ACCESS_QUANTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return GchCar.GCH_CAR.CAR_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return GchCar.GCH_CAR.IMGURL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return GchCar.GCH_CAR.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return GchCar.GCH_CAR.CREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return GchCar.GCH_CAR.CREATEUSER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return GchCar.GCH_CAR.ISDELETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return GchCar.GCH_CAR.UPDATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return GchCar.GCH_CAR.UPDATEUSER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return GchCar.GCH_CAR.ALIF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return GchCar.GCH_CAR.XJ_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return GchCar.GCH_CAR.AUTH_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field15() {
        return GchCar.GCH_CAR.ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field16() {
        return GchCar.GCH_CAR.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return GchCar.GCH_CAR.DISPLACEMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCarModelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getAccessQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCarName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getImgurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCreateuser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getIsdelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getUpdatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getUpdateuser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getAlif();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getXjCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getAuthPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value15() {
        return getOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value16() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getDisplacement();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarRecord value2(String value) {
        setCarModelId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarRecord value3(Integer value) {
        setAccessQuantity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarRecord value4(String value) {
        setCarName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarRecord value5(String value) {
        setImgurl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarRecord value6(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarRecord value7(Timestamp value) {
        setCreatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarRecord value8(String value) {
        setCreateuser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarRecord value9(Integer value) {
        setIsdelete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarRecord value10(Timestamp value) {
        setUpdatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarRecord value11(String value) {
        setUpdateuser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarRecord value12(String value) {
        setAlif(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarRecord value13(Integer value) {
        setXjCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarRecord value14(Integer value) {
        setAuthPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarRecord value15(Integer value) {
        setOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarRecord value16(Byte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarRecord value17(String value) {
        setDisplacement(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarRecord values(String value1, String value2, Integer value3, String value4, String value5, String value6, Timestamp value7, String value8, Integer value9, Timestamp value10, String value11, String value12, Integer value13, Integer value14, Integer value15, Byte value16, String value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GchCarRecord
     */
    public GchCarRecord() {
        super(GchCar.GCH_CAR);
    }

    /**
     * Create a detached, initialised GchCarRecord
     */
    public GchCarRecord(String id, String carModelId, Integer accessQuantity, String carName, String imgurl, String description, Timestamp createtime, String createuser, Integer isdelete, Timestamp updatetime, String updateuser, String alif, Integer xjCount, Integer authPrice, Integer order, Byte status, String displacement) {
        super(GchCar.GCH_CAR);

        set(0, id);
        set(1, carModelId);
        set(2, accessQuantity);
        set(3, carName);
        set(4, imgurl);
        set(5, description);
        set(6, createtime);
        set(7, createuser);
        set(8, isdelete);
        set(9, updatetime);
        set(10, updateuser);
        set(11, alif);
        set(12, xjCount);
        set(13, authPrice);
        set(14, order);
        set(15, status);
        set(16, displacement);
    }
}
