/**
 * This class is generated by jOOQ
 */
package com.lrest.server.jooqmodel.tables.records;


import com.lrest.server.jooqmodel.tables.GchCarActivities;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GchCarActivitiesRecord extends UpdatableRecordImpl<GchCarActivitiesRecord> implements Record16<Integer, Integer, String, String, String, Integer, Integer, Integer, Timestamp, String, Timestamp, String, Integer, Integer, String, String> {

    private static final long serialVersionUID = -1809617920;

    /**
     * Setter for <code>gouchehui2.0.gch_car_activities.id</code>. 主键ID
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_activities.id</code>. 主键ID
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_activities.activity_id</code>. 活动ID
     */
    public void setActivityId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_activities.activity_id</code>. 活动ID
     */
    public Integer getActivityId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_activities.activity_number</code>. 活动编号
     */
    public void setActivityNumber(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_activities.activity_number</code>. 活动编号
     */
    public String getActivityNumber() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_activities.car_id</code>. 车款id
     */
    public void setCarId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_activities.car_id</code>. 车款id
     */
    public String getCarId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_activities.car_price_id</code>. 报价ID
     */
    public void setCarPriceId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_activities.car_price_id</code>. 报价ID
     */
    public String getCarPriceId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_activities.type</code>. 1:立即购买2：马上抢，3：直降，4：打折
     */
    public void setType(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_activities.type</code>. 1:立即购买2：马上抢，3：直降，4：打折
     */
    public Integer getType() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_activities.buyer_count</code>. 购买者数量
     */
    public void setBuyerCount(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_activities.buyer_count</code>. 购买者数量
     */
    public Integer getBuyerCount() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_activities.status</code>. 状态（1：关闭，2：开启）
     */
    public void setStatus(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_activities.status</code>. 状态（1：关闭，2：开启）
     */
    public Integer getStatus() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_activities.createtime</code>.
     */
    public void setCreatetime(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_activities.createtime</code>.
     */
    public Timestamp getCreatetime() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_activities.createuser</code>.
     */
    public void setCreateuser(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_activities.createuser</code>.
     */
    public String getCreateuser() {
        return (String) get(9);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_activities.updatetime</code>.
     */
    public void setUpdatetime(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_activities.updatetime</code>.
     */
    public Timestamp getUpdatetime() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_activities.updateuser</code>.
     */
    public void setUpdateuser(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_activities.updateuser</code>.
     */
    public String getUpdateuser() {
        return (String) get(11);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_activities.isdelete</code>.
     */
    public void setIsdelete(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_activities.isdelete</code>.
     */
    public Integer getIsdelete() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_activities.sort</code>. 排序
     */
    public void setSort(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_activities.sort</code>. 排序
     */
    public Integer getSort() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_activities.group_id</code>. 分组ID
     */
    public void setGroupId(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_activities.group_id</code>. 分组ID
     */
    public String getGroupId() {
        return (String) get(14);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_car_activities.group_name</code>. 组名
     */
    public void setGroupName(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_car_activities.group_name</code>. 组名
     */
    public String getGroupName() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Integer, Integer, String, String, String, Integer, Integer, Integer, Timestamp, String, Timestamp, String, Integer, Integer, String, String> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Integer, Integer, String, String, String, Integer, Integer, Integer, Timestamp, String, Timestamp, String, Integer, Integer, String, String> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return GchCarActivities.GCH_CAR_ACTIVITIES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return GchCarActivities.GCH_CAR_ACTIVITIES.ACTIVITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return GchCarActivities.GCH_CAR_ACTIVITIES.ACTIVITY_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return GchCarActivities.GCH_CAR_ACTIVITIES.CAR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return GchCarActivities.GCH_CAR_ACTIVITIES.CAR_PRICE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return GchCarActivities.GCH_CAR_ACTIVITIES.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return GchCarActivities.GCH_CAR_ACTIVITIES.BUYER_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return GchCarActivities.GCH_CAR_ACTIVITIES.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return GchCarActivities.GCH_CAR_ACTIVITIES.CREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return GchCarActivities.GCH_CAR_ACTIVITIES.CREATEUSER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return GchCarActivities.GCH_CAR_ACTIVITIES.UPDATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return GchCarActivities.GCH_CAR_ACTIVITIES.UPDATEUSER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return GchCarActivities.GCH_CAR_ACTIVITIES.ISDELETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return GchCarActivities.GCH_CAR_ACTIVITIES.SORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return GchCarActivities.GCH_CAR_ACTIVITIES.GROUP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return GchCarActivities.GCH_CAR_ACTIVITIES.GROUP_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getActivityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getActivityNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCarId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCarPriceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getBuyerCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getCreateuser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getUpdatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getUpdateuser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getIsdelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getGroupName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarActivitiesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarActivitiesRecord value2(Integer value) {
        setActivityId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarActivitiesRecord value3(String value) {
        setActivityNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarActivitiesRecord value4(String value) {
        setCarId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarActivitiesRecord value5(String value) {
        setCarPriceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarActivitiesRecord value6(Integer value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarActivitiesRecord value7(Integer value) {
        setBuyerCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarActivitiesRecord value8(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarActivitiesRecord value9(Timestamp value) {
        setCreatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarActivitiesRecord value10(String value) {
        setCreateuser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarActivitiesRecord value11(Timestamp value) {
        setUpdatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarActivitiesRecord value12(String value) {
        setUpdateuser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarActivitiesRecord value13(Integer value) {
        setIsdelete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarActivitiesRecord value14(Integer value) {
        setSort(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarActivitiesRecord value15(String value) {
        setGroupId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarActivitiesRecord value16(String value) {
        setGroupName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarActivitiesRecord values(Integer value1, Integer value2, String value3, String value4, String value5, Integer value6, Integer value7, Integer value8, Timestamp value9, String value10, Timestamp value11, String value12, Integer value13, Integer value14, String value15, String value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GchCarActivitiesRecord
     */
    public GchCarActivitiesRecord() {
        super(GchCarActivities.GCH_CAR_ACTIVITIES);
    }

    /**
     * Create a detached, initialised GchCarActivitiesRecord
     */
    public GchCarActivitiesRecord(Integer id, Integer activityId, String activityNumber, String carId, String carPriceId, Integer type, Integer buyerCount, Integer status, Timestamp createtime, String createuser, Timestamp updatetime, String updateuser, Integer isdelete, Integer sort, String groupId, String groupName) {
        super(GchCarActivities.GCH_CAR_ACTIVITIES);

        set(0, id);
        set(1, activityId);
        set(2, activityNumber);
        set(3, carId);
        set(4, carPriceId);
        set(5, type);
        set(6, buyerCount);
        set(7, status);
        set(8, createtime);
        set(9, createuser);
        set(10, updatetime);
        set(11, updateuser);
        set(12, isdelete);
        set(13, sort);
        set(14, groupId);
        set(15, groupName);
    }
}
