/**
 * This class is generated by jOOQ
 */
package com.lrest.server.jooqmodel.tables.records;


import com.lrest.server.jooqmodel.tables.GchPay;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 询价定车支付表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GchPayRecord extends UpdatableRecordImpl<GchPayRecord> {

    private static final long serialVersionUID = 2141246726;

    /**
     * Setter for <code>gouchehui2.0.gch_pay.id</code>. 订单ID
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.id</code>. 订单ID
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.out_trade_no</code>. 订单号
     */
    public void setOutTradeNo(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.out_trade_no</code>. 订单号
     */
    public String getOutTradeNo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.user_id</code>. 购车人平台账号
     */
    public void setUserId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.user_id</code>. 购车人平台账号
     */
    public String getUserId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.carstyle</code>. 品牌+车型(例 奥迪A4L）
     */
    public void setCarstyle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.carstyle</code>. 品牌+车型(例 奥迪A4L）
     */
    public String getCarstyle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.brand_id</code>. 品牌ID
     */
    public void setBrandId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.brand_id</code>. 品牌ID
     */
    public String getBrandId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.brand_name</code>. 品牌名称
     */
    public void setBrandName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.brand_name</code>. 品牌名称
     */
    public String getBrandName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.car_model_id</code>. 车型ID
     */
    public void setCarModelId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.car_model_id</code>. 车型ID
     */
    public String getCarModelId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.car_model_name</code>. 车型名称
     */
    public void setCarModelName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.car_model_name</code>. 车型名称
     */
    public String getCarModelName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.car_id</code>. 车款ID
     */
    public void setCarId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.car_id</code>. 车款ID
     */
    public String getCarId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.car_name</code>. 车款名称
     */
    public void setCarName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.car_name</code>. 车款名称
     */
    public String getCarName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.exterior_color_id</code>. 外观颜色ID
     */
    public void setExteriorColorId(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.exterior_color_id</code>. 外观颜色ID
     */
    public String getExteriorColorId() {
        return (String) get(10);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.exterior_color_name</code>. 汽车颜色名字
     */
    public void setExteriorColorName(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.exterior_color_name</code>. 汽车颜色名字
     */
    public String getExteriorColorName() {
        return (String) get(11);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.exterior_color_value</code>. 外观颜色值
     */
    public void setExteriorColorValue(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.exterior_color_value</code>. 外观颜色值
     */
    public String getExteriorColorValue() {
        return (String) get(12);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.interior_color_id</code>. 内饰颜色ID
     */
    public void setInteriorColorId(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.interior_color_id</code>. 内饰颜色ID
     */
    public String getInteriorColorId() {
        return (String) get(13);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.interior_color_name</code>. 内饰颜色名字
     */
    public void setInteriorColorName(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.interior_color_name</code>. 内饰颜色名字
     */
    public String getInteriorColorName() {
        return (String) get(14);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.interior_color_value</code>. 内饰颜色值
     */
    public void setInteriorColorValue(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.interior_color_value</code>. 内饰颜色值
     */
    public String getInteriorColorValue() {
        return (String) get(15);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.exterior_img</code>. 外观颜色图片（或者活动图片）
     */
    public void setExteriorImg(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.exterior_img</code>. 外观颜色图片（或者活动图片）
     */
    public String getExteriorImg() {
        return (String) get(16);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.money</code>. 支付金额
     */
    public void setMoney(BigDecimal value) {
        set(17, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.money</code>. 支付金额
     */
    public BigDecimal getMoney() {
        return (BigDecimal) get(17);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.order_money</code>. 原始订单价格
     */
    public void setOrderMoney(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.order_money</code>. 原始订单价格
     */
    public Integer getOrderMoney() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.ticket_money</code>. 优惠券金额
     */
    public void setTicketMoney(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.ticket_money</code>. 优惠券金额
     */
    public Integer getTicketMoney() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.status</code>. 0未支付 ，1已支付（未完善），2已失效，3审核中,4通过审核，5未通过审核，6出库中，7提车中，8已完成，9支付中，10支付失败，11支付取消
     */
    public void setStatus(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.status</code>. 0未支付 ，1已支付（未完善），2已失效，3审核中,4通过审核，5未通过审核，6出库中，7提车中，8已完成，9支付中，10支付失败，11支付取消
     */
    public Integer getStatus() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.status_track</code>. 询价订单状态（1：未跟踪，2：已跟踪）
     */
    public void setStatusTrack(Integer value) {
        set(21, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.status_track</code>. 询价订单状态（1：未跟踪，2：已跟踪）
     */
    public Integer getStatusTrack() {
        return (Integer) get(21);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.pay_obj</code>. 支付对象(1:询价2:订金,3:一键询价,4:一元抢（双十一）)
     */
    public void setPayObj(Byte value) {
        set(22, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.pay_obj</code>. 支付对象(1:询价2:订金,3:一键询价,4:一元抢（双十一）)
     */
    public Byte getPayObj() {
        return (Byte) get(22);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.type</code>. 车辆类型 1、底价车 2、特价车
     */
    public void setType(Integer value) {
        set(23, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.type</code>. 车辆类型 1、底价车 2、特价车
     */
    public Integer getType() {
        return (Integer) get(23);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.buy_way</code>. 付款方式
     */
    public void setBuyWay(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.buy_way</code>. 付款方式
     */
    public String getBuyWay() {
        return (String) get(24);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.buyer_name</code>. 购买人姓名
     */
    public void setBuyerName(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.buyer_name</code>. 购买人姓名
     */
    public String getBuyerName() {
        return (String) get(25);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.buyer_tel</code>. 支付人手机
     */
    public void setBuyerTel(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.buyer_tel</code>. 支付人手机
     */
    public String getBuyerTel() {
        return (String) get(26);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.buy_time</code>. 购车时间
     */
    public void setBuyTime(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.buy_time</code>. 购车时间
     */
    public String getBuyTime() {
        return (String) get(27);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.car_mode</code>. 提车方式
     */
    public void setCarMode(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.car_mode</code>. 提车方式
     */
    public String getCarMode() {
        return (String) get(28);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.pay_way</code>. 支付方式(支付宝,微信支付等)
     */
    public void setPayWay(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.pay_way</code>. 支付方式(支付宝,微信支付等)
     */
    public String getPayWay() {
        return (String) get(29);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.pay_ip</code>. 支付人ip
     */
    public void setPayIp(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.pay_ip</code>. 支付人ip
     */
    public String getPayIp() {
        return (String) get(30);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.card_place</code>. 上牌地点
     */
    public void setCardPlace(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.card_place</code>. 上牌地点
     */
    public String getCardPlace() {
        return (String) get(31);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.pay_err_code_des</code>. 支付失败返回描述
     */
    public void setPayErrCodeDes(String value) {
        set(32, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.pay_err_code_des</code>. 支付失败返回描述
     */
    public String getPayErrCodeDes() {
        return (String) get(32);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.sign</code>. 微信支付签名
     */
    public void setSign(String value) {
        set(33, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.sign</code>. 微信支付签名
     */
    public String getSign() {
        return (String) get(33);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.callback</code>. 支付完回调地址
     */
    public void setCallback(String value) {
        set(34, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.callback</code>. 支付完回调地址
     */
    public String getCallback() {
        return (String) get(34);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.url</code>. 支付完回调地址
     */
    public void setUrl(String value) {
        set(35, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.url</code>. 支付完回调地址
     */
    public String getUrl() {
        return (String) get(35);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.from_caractivityid</code>. 来源活动车款ID
     */
    public void setFromCaractivityid(Integer value) {
        set(36, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.from_caractivityid</code>. 来源活动车款ID
     */
    public Integer getFromCaractivityid() {
        return (Integer) get(36);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.from_order</code>. 订单来源
     */
    public void setFromOrder(String value) {
        set(37, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.from_order</code>. 订单来源
     */
    public String getFromOrder() {
        return (String) get(37);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.from_activityid</code>. 订单来源活动id
     */
    public void setFromActivityid(Integer value) {
        set(38, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.from_activityid</code>. 订单来源活动id
     */
    public Integer getFromActivityid() {
        return (Integer) get(38);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.ticket_number</code>. 优惠券号
     */
    public void setTicketNumber(String value) {
        set(39, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.ticket_number</code>. 优惠券号
     */
    public String getTicketNumber() {
        return (String) get(39);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.user_remark</code>. 用户备注
     */
    public void setUserRemark(String value) {
        set(40, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.user_remark</code>. 用户备注
     */
    public String getUserRemark() {
        return (String) get(40);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.cus_name</code>. 客服姓名
     */
    public void setCusName(String value) {
        set(41, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.cus_name</code>. 客服姓名
     */
    public String getCusName() {
        return (String) get(41);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.cus_remark</code>. 客服备注
     */
    public void setCusRemark(String value) {
        set(42, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.cus_remark</code>. 客服备注
     */
    public String getCusRemark() {
        return (String) get(42);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.cus_character</code>. 客服-角色判读
     */
    public void setCusCharacter(String value) {
        set(43, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.cus_character</code>. 客服-角色判读
     */
    public String getCusCharacter() {
        return (String) get(43);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.ID_imgurl1</code>. 身份证正面图片
     */
    public void setIdImgurl1(String value) {
        set(44, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.ID_imgurl1</code>. 身份证正面图片
     */
    public String getIdImgurl1() {
        return (String) get(44);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.ID_imgurl2</code>. 身份证反面
     */
    public void setIdImgurl2(String value) {
        set(45, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.ID_imgurl2</code>. 身份证反面
     */
    public String getIdImgurl2() {
        return (String) get(45);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.low_price</code>. 成交底价
     */
    public void setLowPrice(String value) {
        set(46, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.low_price</code>. 成交底价
     */
    public String getLowPrice() {
        return (String) get(46);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.low_price_city_name</code>. 成交底价城市名称
     */
    public void setLowPriceCityName(String value) {
        set(47, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.low_price_city_name</code>. 成交底价城市名称
     */
    public String getLowPriceCityName() {
        return (String) get(47);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.car_special_id</code>. 特价车ID
     */
    public void setCarSpecialId(String value) {
        set(48, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.car_special_id</code>. 特价车ID
     */
    public String getCarSpecialId() {
        return (String) get(48);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.car_price_id</code>. 底价车id
     */
    public void setCarPriceId(String value) {
        set(49, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.car_price_id</code>. 底价车id
     */
    public String getCarPriceId() {
        return (String) get(49);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.id_4s</code>. 4s店id
     */
    public void setId_4s(String value) {
        set(50, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.id_4s</code>. 4s店id
     */
    public String getId_4s() {
        return (String) get(50);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.name_4s</code>. 4s店名
     */
    public void setName_4s(String value) {
        set(51, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.name_4s</code>. 4s店名
     */
    public String getName_4s() {
        return (String) get(51);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.isread</code>. 是否读 1：未读；2：已读
     */
    public void setIsread(Byte value) {
        set(52, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.isread</code>. 是否读 1：未读；2：已读
     */
    public Byte getIsread() {
        return (Byte) get(52);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.credit_fee</code>. 贷款手续费
     */
    public void setCreditFee(Integer value) {
        set(53, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.credit_fee</code>. 贷款手续费
     */
    public Integer getCreditFee() {
        return (Integer) get(53);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.insurance</code>. 是否购买保险
     */
    public void setInsurance(String value) {
        set(54, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.insurance</code>. 是否购买保险
     */
    public String getInsurance() {
        return (String) get(54);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.compulsory_insurance</code>. 交强险
     */
    public void setCompulsoryInsurance(String value) {
        set(55, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.compulsory_insurance</code>. 交强险
     */
    public String getCompulsoryInsurance() {
        return (String) get(55);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.cess</code>. 税率
     */
    public void setCess(String value) {
        set(56, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.cess</code>. 税率
     */
    public String getCess() {
        return (String) get(56);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.licensing_fees</code>. 上牌费
     */
    public void setLicensingFees(String value) {
        set(57, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.licensing_fees</code>. 上牌费
     */
    public String getLicensingFees() {
        return (String) get(57);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.travel_tax</code>. 车船使用税
     */
    public void setTravelTax(String value) {
        set(58, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.travel_tax</code>. 车船使用税
     */
    public String getTravelTax() {
        return (String) get(58);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.car_loss_dang</code>. 车辆损失险
     */
    public void setCarLossDang(String value) {
        set(59, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.car_loss_dang</code>. 车辆损失险
     */
    public String getCarLossDang() {
        return (String) get(59);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.liability</code>. 第三方责任险
     */
    public void setLiability(String value) {
        set(60, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.liability</code>. 第三方责任险
     */
    public String getLiability() {
        return (String) get(60);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.car_liability</code>. 车上人员责任险
     */
    public void setCarLiability(String value) {
        set(61, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.car_liability</code>. 车上人员责任险
     */
    public String getCarLiability() {
        return (String) get(61);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.deductible_special</code>. 附加不计免赔特约
     */
    public void setDeductibleSpecial(String value) {
        set(62, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.deductible_special</code>. 附加不计免赔特约
     */
    public String getDeductibleSpecial() {
        return (String) get(62);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.is_distribute</code>. 是否是重新分配的订单（0：未分配过，1，重新分配过）
     */
    public void setIsDistribute(Integer value) {
        set(63, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.is_distribute</code>. 是否是重新分配的订单（0：未分配过，1，重新分配过）
     */
    public Integer getIsDistribute() {
        return (Integer) get(63);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.createtime</code>. 创建时间
     */
    public void setCreatetime(Timestamp value) {
        set(64, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.createtime</code>. 创建时间
     */
    public Timestamp getCreatetime() {
        return (Timestamp) get(64);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.isdelete</code>. 是否删除
     */
    public void setIsdelete(Integer value) {
        set(65, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.isdelete</code>. 是否删除
     */
    public Integer getIsdelete() {
        return (Integer) get(65);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.updatetime</code>. 更新时间
     */
    public void setUpdatetime(String value) {
        set(66, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.updatetime</code>. 更新时间
     */
    public String getUpdatetime() {
        return (String) get(66);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.updatetime_3</code>. 订单详情对应2的更新时间
     */
    public void setUpdatetime_3(String value) {
        set(67, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.updatetime_3</code>. 订单详情对应2的更新时间
     */
    public String getUpdatetime_3() {
        return (String) get(67);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.updateuser_3</code>. 订单详情对应2的更新人
     */
    public void setUpdateuser_3(String value) {
        set(68, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.updateuser_3</code>. 订单详情对应2的更新人
     */
    public String getUpdateuser_3() {
        return (String) get(68);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.updateuser_4</code>. 订单详情对应3的更新人
     */
    public void setUpdateuser_4(String value) {
        set(69, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.updateuser_4</code>. 订单详情对应3的更新人
     */
    public String getUpdateuser_4() {
        return (String) get(69);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.updatetime_4</code>. 订单详情对应3的更新时间
     */
    public void setUpdatetime_4(String value) {
        set(70, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.updatetime_4</code>. 订单详情对应3的更新时间
     */
    public String getUpdatetime_4() {
        return (String) get(70);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.updateuser_5</code>. 订单详情对应4的更新人
     */
    public void setUpdateuser_5(String value) {
        set(71, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.updateuser_5</code>. 订单详情对应4的更新人
     */
    public String getUpdateuser_5() {
        return (String) get(71);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_pay.updatetime_5</code>. 订单详情对应4的更新时间
     */
    public void setUpdatetime_5(String value) {
        set(72, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_pay.updatetime_5</code>. 订单详情对应4的更新时间
     */
    public String getUpdatetime_5() {
        return (String) get(72);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GchPayRecord
     */
    public GchPayRecord() {
        super(GchPay.GCH_PAY);
    }

    /**
     * Create a detached, initialised GchPayRecord
     */
    public GchPayRecord(String id, String outTradeNo, String userId, String carstyle, String brandId, String brandName, String carModelId, String carModelName, String carId, String carName, String exteriorColorId, String exteriorColorName, String exteriorColorValue, String interiorColorId, String interiorColorName, String interiorColorValue, String exteriorImg, BigDecimal money, Integer orderMoney, Integer ticketMoney, Integer status, Integer statusTrack, Byte payObj, Integer type, String buyWay, String buyerName, String buyerTel, String buyTime, String carMode, String payWay, String payIp, String cardPlace, String payErrCodeDes, String sign, String callback, String url, Integer fromCaractivityid, String fromOrder, Integer fromActivityid, String ticketNumber, String userRemark, String cusName, String cusRemark, String cusCharacter, String idImgurl1, String idImgurl2, String lowPrice, String lowPriceCityName, String carSpecialId, String carPriceId, String id_4s, String name_4s, Byte isread, Integer creditFee, String insurance, String compulsoryInsurance, String cess, String licensingFees, String travelTax, String carLossDang, String liability, String carLiability, String deductibleSpecial, Integer isDistribute, Timestamp createtime, Integer isdelete, String updatetime, String updatetime_3, String updateuser_3, String updateuser_4, String updatetime_4, String updateuser_5, String updatetime_5) {
        super(GchPay.GCH_PAY);

        set(0, id);
        set(1, outTradeNo);
        set(2, userId);
        set(3, carstyle);
        set(4, brandId);
        set(5, brandName);
        set(6, carModelId);
        set(7, carModelName);
        set(8, carId);
        set(9, carName);
        set(10, exteriorColorId);
        set(11, exteriorColorName);
        set(12, exteriorColorValue);
        set(13, interiorColorId);
        set(14, interiorColorName);
        set(15, interiorColorValue);
        set(16, exteriorImg);
        set(17, money);
        set(18, orderMoney);
        set(19, ticketMoney);
        set(20, status);
        set(21, statusTrack);
        set(22, payObj);
        set(23, type);
        set(24, buyWay);
        set(25, buyerName);
        set(26, buyerTel);
        set(27, buyTime);
        set(28, carMode);
        set(29, payWay);
        set(30, payIp);
        set(31, cardPlace);
        set(32, payErrCodeDes);
        set(33, sign);
        set(34, callback);
        set(35, url);
        set(36, fromCaractivityid);
        set(37, fromOrder);
        set(38, fromActivityid);
        set(39, ticketNumber);
        set(40, userRemark);
        set(41, cusName);
        set(42, cusRemark);
        set(43, cusCharacter);
        set(44, idImgurl1);
        set(45, idImgurl2);
        set(46, lowPrice);
        set(47, lowPriceCityName);
        set(48, carSpecialId);
        set(49, carPriceId);
        set(50, id_4s);
        set(51, name_4s);
        set(52, isread);
        set(53, creditFee);
        set(54, insurance);
        set(55, compulsoryInsurance);
        set(56, cess);
        set(57, licensingFees);
        set(58, travelTax);
        set(59, carLossDang);
        set(60, liability);
        set(61, carLiability);
        set(62, deductibleSpecial);
        set(63, isDistribute);
        set(64, createtime);
        set(65, isdelete);
        set(66, updatetime);
        set(67, updatetime_3);
        set(68, updateuser_3);
        set(69, updateuser_4);
        set(70, updatetime_4);
        set(71, updateuser_5);
        set(72, updatetime_5);
    }
}
