/**
 * This class is generated by jOOQ
 */
package com.lrest.server.jooqmodel.tables.records;


import com.lrest.server.jooqmodel.tables.GchSpecialPriceCarTrend;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 特价车
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GchSpecialPriceCarTrendRecord extends UpdatableRecordImpl<GchSpecialPriceCarTrendRecord> implements Record16<String, String, String, String, String, String, String, Integer, Integer, Timestamp, Timestamp, Integer, Byte, String, Timestamp, String> {

    private static final long serialVersionUID = 1979529295;

    /**
     * Setter for <code>gouchehui2.0.gch_special_price_car_trend.id</code>. 主键
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_special_price_car_trend.id</code>. 主键
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_special_price_car_trend.special_price_car</code>. gch_special_price_car表的ID
     */
    public void setSpecialPriceCar(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_special_price_car_trend.special_price_car</code>. gch_special_price_car表的ID
     */
    public String getSpecialPriceCar() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_special_price_car_trend.user_id</code>. 关联用户ID
     */
    public void setUserId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_special_price_car_trend.user_id</code>. 关联用户ID
     */
    public String getUserId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_special_price_car_trend.interior_color_id</code>. 内饰颜色ID
     */
    public void setInteriorColorId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_special_price_car_trend.interior_color_id</code>. 内饰颜色ID
     */
    public String getInteriorColorId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_special_price_car_trend.exterior_color_id</code>. 外观颜色ID
     */
    public void setExteriorColorId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_special_price_car_trend.exterior_color_id</code>. 外观颜色ID
     */
    public String getExteriorColorId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_special_price_car_trend.car_image</code>. 车款图片
     */
    public void setCarImage(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_special_price_car_trend.car_image</code>. 车款图片
     */
    public String getCarImage() {
        return (String) get(5);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_special_price_car_trend.car_id</code>. 汽车ID
     */
    public void setCarId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_special_price_car_trend.car_id</code>. 汽车ID
     */
    public String getCarId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_special_price_car_trend.price</code>. 价格
     */
    public void setPrice(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_special_price_car_trend.price</code>. 价格
     */
    public Integer getPrice() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_special_price_car_trend.special_price</code>. 特价
     */
    public void setSpecialPrice(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_special_price_car_trend.special_price</code>. 特价
     */
    public Integer getSpecialPrice() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_special_price_car_trend.start_date</code>. 开始时间
     */
    public void setStartDate(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_special_price_car_trend.start_date</code>. 开始时间
     */
    public Timestamp getStartDate() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_special_price_car_trend.end_date</code>. 结束时间
     */
    public void setEndDate(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_special_price_car_trend.end_date</code>. 结束时间
     */
    public Timestamp getEndDate() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_special_price_car_trend.number</code>. 活动数量
     */
    public void setNumber(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_special_price_car_trend.number</code>. 活动数量
     */
    public Integer getNumber() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_special_price_car_trend.status</code>. 特价车状态（1：审核中，2：未开始，3：在售，4：停售，5：过期，6：审核失败）
     */
    public void setStatus(Byte value) {
        set(12, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_special_price_car_trend.status</code>. 特价车状态（1：审核中，2：未开始，3：在售，4：停售，5：过期，6：审核失败）
     */
    public Byte getStatus() {
        return (Byte) get(12);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_special_price_car_trend.description</code>. 活动说明
     */
    public void setDescription(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_special_price_car_trend.description</code>. 活动说明
     */
    public String getDescription() {
        return (String) get(13);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_special_price_car_trend.createtime</code>. 创建时间
     */
    public void setCreatetime(Timestamp value) {
        set(14, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_special_price_car_trend.createtime</code>. 创建时间
     */
    public Timestamp getCreatetime() {
        return (Timestamp) get(14);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_special_price_car_trend.createuser</code>. 创建人
     */
    public void setCreateuser(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_special_price_car_trend.createuser</code>. 创建人
     */
    public String getCreateuser() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<String, String, String, String, String, String, String, Integer, Integer, Timestamp, Timestamp, Integer, Byte, String, Timestamp, String> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<String, String, String, String, String, String, String, Integer, Integer, Timestamp, Timestamp, Integer, Byte, String, Timestamp, String> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return GchSpecialPriceCarTrend.GCH_SPECIAL_PRICE_CAR_TREND.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return GchSpecialPriceCarTrend.GCH_SPECIAL_PRICE_CAR_TREND.SPECIAL_PRICE_CAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return GchSpecialPriceCarTrend.GCH_SPECIAL_PRICE_CAR_TREND.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return GchSpecialPriceCarTrend.GCH_SPECIAL_PRICE_CAR_TREND.INTERIOR_COLOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return GchSpecialPriceCarTrend.GCH_SPECIAL_PRICE_CAR_TREND.EXTERIOR_COLOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return GchSpecialPriceCarTrend.GCH_SPECIAL_PRICE_CAR_TREND.CAR_IMAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return GchSpecialPriceCarTrend.GCH_SPECIAL_PRICE_CAR_TREND.CAR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return GchSpecialPriceCarTrend.GCH_SPECIAL_PRICE_CAR_TREND.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return GchSpecialPriceCarTrend.GCH_SPECIAL_PRICE_CAR_TREND.SPECIAL_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return GchSpecialPriceCarTrend.GCH_SPECIAL_PRICE_CAR_TREND.START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return GchSpecialPriceCarTrend.GCH_SPECIAL_PRICE_CAR_TREND.END_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return GchSpecialPriceCarTrend.GCH_SPECIAL_PRICE_CAR_TREND.NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field13() {
        return GchSpecialPriceCarTrend.GCH_SPECIAL_PRICE_CAR_TREND.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return GchSpecialPriceCarTrend.GCH_SPECIAL_PRICE_CAR_TREND.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field15() {
        return GchSpecialPriceCarTrend.GCH_SPECIAL_PRICE_CAR_TREND.CREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return GchSpecialPriceCarTrend.GCH_SPECIAL_PRICE_CAR_TREND.CREATEUSER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSpecialPriceCar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getInteriorColorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getExteriorColorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCarImage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCarId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getSpecialPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value13() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value15() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getCreateuser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchSpecialPriceCarTrendRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchSpecialPriceCarTrendRecord value2(String value) {
        setSpecialPriceCar(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchSpecialPriceCarTrendRecord value3(String value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchSpecialPriceCarTrendRecord value4(String value) {
        setInteriorColorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchSpecialPriceCarTrendRecord value5(String value) {
        setExteriorColorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchSpecialPriceCarTrendRecord value6(String value) {
        setCarImage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchSpecialPriceCarTrendRecord value7(String value) {
        setCarId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchSpecialPriceCarTrendRecord value8(Integer value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchSpecialPriceCarTrendRecord value9(Integer value) {
        setSpecialPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchSpecialPriceCarTrendRecord value10(Timestamp value) {
        setStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchSpecialPriceCarTrendRecord value11(Timestamp value) {
        setEndDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchSpecialPriceCarTrendRecord value12(Integer value) {
        setNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchSpecialPriceCarTrendRecord value13(Byte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchSpecialPriceCarTrendRecord value14(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchSpecialPriceCarTrendRecord value15(Timestamp value) {
        setCreatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchSpecialPriceCarTrendRecord value16(String value) {
        setCreateuser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchSpecialPriceCarTrendRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, Integer value8, Integer value9, Timestamp value10, Timestamp value11, Integer value12, Byte value13, String value14, Timestamp value15, String value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GchSpecialPriceCarTrendRecord
     */
    public GchSpecialPriceCarTrendRecord() {
        super(GchSpecialPriceCarTrend.GCH_SPECIAL_PRICE_CAR_TREND);
    }

    /**
     * Create a detached, initialised GchSpecialPriceCarTrendRecord
     */
    public GchSpecialPriceCarTrendRecord(String id, String specialPriceCar, String userId, String interiorColorId, String exteriorColorId, String carImage, String carId, Integer price, Integer specialPrice, Timestamp startDate, Timestamp endDate, Integer number, Byte status, String description, Timestamp createtime, String createuser) {
        super(GchSpecialPriceCarTrend.GCH_SPECIAL_PRICE_CAR_TREND);

        set(0, id);
        set(1, specialPriceCar);
        set(2, userId);
        set(3, interiorColorId);
        set(4, exteriorColorId);
        set(5, carImage);
        set(6, carId);
        set(7, price);
        set(8, specialPrice);
        set(9, startDate);
        set(10, endDate);
        set(11, number);
        set(12, status);
        set(13, description);
        set(14, createtime);
        set(15, createuser);
    }
}
