/**
 * This class is generated by jOOQ
 */
package com.lrest.server.jooqmodel.tables.records;


import com.lrest.server.jooqmodel.tables.GchViewSpecialPriceCar;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GchViewSpecialPriceCarRecord extends TableRecordImpl<GchViewSpecialPriceCarRecord> {

    private static final long serialVersionUID = -1882471147;

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.id</code>. 主键
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.id</code>. 主键
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.user_id</code>. 关联用户ID
     */
    public void setUserId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.user_id</code>. 关联用户ID
     */
    public String getUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.interior_color_id</code>. 内饰颜色ID
     */
    public void setInteriorColorId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.interior_color_id</code>. 内饰颜色ID
     */
    public String getInteriorColorId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.exterior_color_id</code>. 外观颜色ID
     */
    public void setExteriorColorId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.exterior_color_id</code>. 外观颜色ID
     */
    public String getExteriorColorId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.car_image</code>. 车款图片
     */
    public void setCarImage(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.car_image</code>. 车款图片
     */
    public String getCarImage() {
        return (String) get(4);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.car_id</code>. 汽车ID
     */
    public void setCarId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.car_id</code>. 汽车ID
     */
    public String getCarId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.price</code>. 价格
     */
    public void setPrice(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.price</code>. 价格
     */
    public Integer getPrice() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.special_price</code>. 特价
     */
    public void setSpecialPrice(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.special_price</code>. 特价
     */
    public Integer getSpecialPrice() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.start_date</code>. 开始时间
     */
    public void setStartDate(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.start_date</code>. 开始时间
     */
    public Timestamp getStartDate() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.end_date</code>. 结束时间
     */
    public void setEndDate(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.end_date</code>. 结束时间
     */
    public Timestamp getEndDate() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.number</code>. 活动数量
     */
    public void setNumber(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.number</code>. 活动数量
     */
    public Integer getNumber() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.description</code>. 活动说明
     */
    public void setDescription(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.description</code>. 活动说明
     */
    public String getDescription() {
        return (String) get(11);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.attention_count</code>. 关注度
     */
    public void setAttentionCount(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.attention_count</code>. 关注度
     */
    public Integer getAttentionCount() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.isdelete</code>. 是否删除
     */
    public void setIsdelete(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.isdelete</code>. 是否删除
     */
    public Integer getIsdelete() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.exterior_color_name</code>. 名称
     */
    public void setExteriorColorName(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.exterior_color_name</code>. 名称
     */
    public String getExteriorColorName() {
        return (String) get(14);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.car_name</code>. 名称
     */
    public void setCarName(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.car_name</code>. 名称
     */
    public String getCarName() {
        return (String) get(15);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.brand_name</code>. 名称
     */
    public void setBrandName(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.brand_name</code>. 名称
     */
    public String getBrandName() {
        return (String) get(16);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.car_model_name</code>. 名称
     */
    public void setCarModelName(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.car_model_name</code>. 名称
     */
    public String getCarModelName() {
        return (String) get(17);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.brand_id</code>. 所属品牌
     */
    public void setBrandId(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.brand_id</code>. 所属品牌
     */
    public String getBrandId() {
        return (String) get(18);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.car_model_id</code>. 所属车型
     */
    public void setCarModelId(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.car_model_id</code>. 所属车型
     */
    public String getCarModelId() {
        return (String) get(19);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.interior_color_name</code>. 名称
     */
    public void setInteriorColorName(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.interior_color_name</code>. 名称
     */
    public String getInteriorColorName() {
        return (String) get(20);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.car_status</code>. 车款状态 1：在售；0：停售。
     */
    public void setCarStatus(Byte value) {
        set(21, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.car_status</code>. 车款状态 1：在售；0：停售。
     */
    public Byte getCarStatus() {
        return (Byte) get(21);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.brand_alif</code>.
     */
    public void setBrandAlif(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.brand_alif</code>.
     */
    public String getBrandAlif() {
        return (String) get(22);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.auth_price</code>. 官方指导价
     */
    public void setAuthPrice(Integer value) {
        set(23, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.auth_price</code>. 官方指导价
     */
    public Integer getAuthPrice() {
        return (Integer) get(23);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.city_name</code>. 城市名称
     */
    public void setCityName(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.city_name</code>. 城市名称
     */
    public String getCityName() {
        return (String) get(24);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.province_id</code>. 所属省份
     */
    public void setProvinceId(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.province_id</code>. 所属省份
     */
    public String getProvinceId() {
        return (String) get(25);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.user_name</code>. 登录名
     */
    public void setUserName(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.user_name</code>. 登录名
     */
    public String getUserName() {
        return (String) get(26);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.name_4s</code>. 4S店名称
     */
    public void setName_4s(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.name_4s</code>. 4S店名称
     */
    public String getName_4s() {
        return (String) get(27);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.brand_4s</code>. 4S店主营品牌
     */
    public void setBrand_4s(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.brand_4s</code>. 4S店主营品牌
     */
    public String getBrand_4s() {
        return (String) get(28);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.city_id</code>. 城市ID
     */
    public void setCityId(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.city_id</code>. 城市ID
     */
    public String getCityId() {
        return (String) get(29);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.province_name</code>. 省份名称
     */
    public void setProvinceName(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.province_name</code>. 省份名称
     */
    public String getProvinceName() {
        return (String) get(30);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.exterior_img</code>. 图片
     */
    public void setExteriorImg(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.exterior_img</code>. 图片
     */
    public String getExteriorImg() {
        return (String) get(31);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.createtime</code>. 创建时间
     */
    public void setCreatetime(Timestamp value) {
        set(32, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.createtime</code>. 创建时间
     */
    public Timestamp getCreatetime() {
        return (Timestamp) get(32);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.createuser</code>. 创建人
     */
    public void setCreateuser(String value) {
        set(33, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.createuser</code>. 创建人
     */
    public String getCreateuser() {
        return (String) get(33);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.updateuser</code>. 修改人
     */
    public void setUpdateuser(String value) {
        set(34, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.updateuser</code>. 修改人
     */
    public String getUpdateuser() {
        return (String) get(34);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.updatetime</code>. 修改时间
     */
    public void setUpdatetime(Timestamp value) {
        set(35, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.updatetime</code>. 修改时间
     */
    public Timestamp getUpdatetime() {
        return (Timestamp) get(35);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.exterior_color_value</code>. 色值
     */
    public void setExteriorColorValue(String value) {
        set(36, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.exterior_color_value</code>. 色值
     */
    public String getExteriorColorValue() {
        return (String) get(36);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.interior_color_value</code>. 色值
     */
    public void setInteriorColorValue(String value) {
        set(37, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.interior_color_value</code>. 色值
     */
    public String getInteriorColorValue() {
        return (String) get(37);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.status</code>. 特价车状态（1：审核中，2：未开始，3：在售，4：停售，5：过期，6：审核失败）
     */
    public void setStatus(Byte value) {
        set(38, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.status</code>. 特价车状态（1：审核中，2：未开始，3：在售，4：停售，5：过期，6：审核失败）
     */
    public Byte getStatus() {
        return (Byte) get(38);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.remark</code>. 备注(审核不通过）
     */
    public void setRemark(String value) {
        set(39, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.remark</code>. 备注(审核不通过）
     */
    public String getRemark() {
        return (String) get(39);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.displacement</code>. 排量
     */
    public void setDisplacement(String value) {
        set(40, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.displacement</code>. 排量
     */
    public String getDisplacement() {
        return (String) get(40);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.discount</code>.
     */
    public void setDiscount(Long value) {
        set(41, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.discount</code>.
     */
    public Long getDiscount() {
        return (Long) get(41);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_special_price_car.client</code>. 客户端(1:pc,2:手机web端)
     */
    public void setClient(Integer value) {
        set(42, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_special_price_car.client</code>. 客户端(1:pc,2:手机web端)
     */
    public Integer getClient() {
        return (Integer) get(42);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GchViewSpecialPriceCarRecord
     */
    public GchViewSpecialPriceCarRecord() {
        super(GchViewSpecialPriceCar.GCH_VIEW_SPECIAL_PRICE_CAR);
    }

    /**
     * Create a detached, initialised GchViewSpecialPriceCarRecord
     */
    public GchViewSpecialPriceCarRecord(String id, String userId, String interiorColorId, String exteriorColorId, String carImage, String carId, Integer price, Integer specialPrice, Timestamp startDate, Timestamp endDate, Integer number, String description, Integer attentionCount, Integer isdelete, String exteriorColorName, String carName, String brandName, String carModelName, String brandId, String carModelId, String interiorColorName, Byte carStatus, String brandAlif, Integer authPrice, String cityName, String provinceId, String userName, String name_4s, String brand_4s, String cityId, String provinceName, String exteriorImg, Timestamp createtime, String createuser, String updateuser, Timestamp updatetime, String exteriorColorValue, String interiorColorValue, Byte status, String remark, String displacement, Long discount, Integer client) {
        super(GchViewSpecialPriceCar.GCH_VIEW_SPECIAL_PRICE_CAR);

        set(0, id);
        set(1, userId);
        set(2, interiorColorId);
        set(3, exteriorColorId);
        set(4, carImage);
        set(5, carId);
        set(6, price);
        set(7, specialPrice);
        set(8, startDate);
        set(9, endDate);
        set(10, number);
        set(11, description);
        set(12, attentionCount);
        set(13, isdelete);
        set(14, exteriorColorName);
        set(15, carName);
        set(16, brandName);
        set(17, carModelName);
        set(18, brandId);
        set(19, carModelId);
        set(20, interiorColorName);
        set(21, carStatus);
        set(22, brandAlif);
        set(23, authPrice);
        set(24, cityName);
        set(25, provinceId);
        set(26, userName);
        set(27, name_4s);
        set(28, brand_4s);
        set(29, cityId);
        set(30, provinceName);
        set(31, exteriorImg);
        set(32, createtime);
        set(33, createuser);
        set(34, updateuser);
        set(35, updatetime);
        set(36, exteriorColorValue);
        set(37, interiorColorValue);
        set(38, status);
        set(39, remark);
        set(40, displacement);
        set(41, discount);
        set(42, client);
    }
}
