/**
 * This class is generated by jOOQ
 */
package com.lrest.server.jooqmodel.tables.records;


import com.lrest.server.jooqmodel.tables.V3UserDevice;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * ios android web
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class V3UserDeviceRecord extends UpdatableRecordImpl<V3UserDeviceRecord> implements Record9<String, String, String, Timestamp, Timestamp, String, String, String, String> {

    private static final long serialVersionUID = 1360890518;

    /**
     * Setter for <code>gouchehui2.0.v3_user_device.userid</code>.
     */
    public void setUserid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>gouchehui2.0.v3_user_device.userid</code>.
     */
    public String getUserid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>gouchehui2.0.v3_user_device.deviceid</code>. 由设备自己上报 暂不使用
     */
    public void setDeviceid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gouchehui2.0.v3_user_device.deviceid</code>. 由设备自己上报 暂不使用
     */
    public String getDeviceid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gouchehui2.0.v3_user_device.token</code>.
     */
    public void setToken(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gouchehui2.0.v3_user_device.token</code>.
     */
    public String getToken() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gouchehui2.0.v3_user_device.token_creat_at</code>.
     */
    public void setTokenCreatAt(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>gouchehui2.0.v3_user_device.token_creat_at</code>.
     */
    public Timestamp getTokenCreatAt() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>gouchehui2.0.v3_user_device.token_last_login_at</code>.
     */
    public void setTokenLastLoginAt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>gouchehui2.0.v3_user_device.token_last_login_at</code>.
     */
    public Timestamp getTokenLastLoginAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>gouchehui2.0.v3_user_device.device_desc</code>. web is user-agent  
     */
    public void setDeviceDesc(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>gouchehui2.0.v3_user_device.device_desc</code>. web is user-agent  
     */
    public String getDeviceDesc() {
        return (String) get(5);
    }

    /**
     * Setter for <code>gouchehui2.0.v3_user_device.device_platform</code>. web app
     */
    public void setDevicePlatform(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>gouchehui2.0.v3_user_device.device_platform</code>. web app
     */
    public String getDevicePlatform() {
        return (String) get(6);
    }

    /**
     * Setter for <code>gouchehui2.0.v3_user_device.device_os</code>.
     */
    public void setDeviceOs(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>gouchehui2.0.v3_user_device.device_os</code>.
     */
    public String getDeviceOs() {
        return (String) get(7);
    }

    /**
     * Setter for <code>gouchehui2.0.v3_user_device.device_browser</code>.
     */
    public void setDeviceBrowser(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>gouchehui2.0.v3_user_device.device_browser</code>.
     */
    public String getDeviceBrowser() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, Timestamp, Timestamp, String, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, Timestamp, Timestamp, String, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return V3UserDevice.V3_USER_DEVICE.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return V3UserDevice.V3_USER_DEVICE.DEVICEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return V3UserDevice.V3_USER_DEVICE.TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return V3UserDevice.V3_USER_DEVICE.TOKEN_CREAT_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return V3UserDevice.V3_USER_DEVICE.TOKEN_LAST_LOGIN_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return V3UserDevice.V3_USER_DEVICE.DEVICE_DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return V3UserDevice.V3_USER_DEVICE.DEVICE_PLATFORM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return V3UserDevice.V3_USER_DEVICE.DEVICE_OS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return V3UserDevice.V3_USER_DEVICE.DEVICE_BROWSER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDeviceid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getTokenCreatAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getTokenLastLoginAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDeviceDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDevicePlatform();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getDeviceOs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getDeviceBrowser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public V3UserDeviceRecord value1(String value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public V3UserDeviceRecord value2(String value) {
        setDeviceid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public V3UserDeviceRecord value3(String value) {
        setToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public V3UserDeviceRecord value4(Timestamp value) {
        setTokenCreatAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public V3UserDeviceRecord value5(Timestamp value) {
        setTokenLastLoginAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public V3UserDeviceRecord value6(String value) {
        setDeviceDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public V3UserDeviceRecord value7(String value) {
        setDevicePlatform(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public V3UserDeviceRecord value8(String value) {
        setDeviceOs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public V3UserDeviceRecord value9(String value) {
        setDeviceBrowser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public V3UserDeviceRecord values(String value1, String value2, String value3, Timestamp value4, Timestamp value5, String value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached V3UserDeviceRecord
     */
    public V3UserDeviceRecord() {
        super(V3UserDevice.V3_USER_DEVICE);
    }

    /**
     * Create a detached, initialised V3UserDeviceRecord
     */
    public V3UserDeviceRecord(String userid, String deviceid, String token, Timestamp tokenCreatAt, Timestamp tokenLastLoginAt, String deviceDesc, String devicePlatform, String deviceOs, String deviceBrowser) {
        super(V3UserDevice.V3_USER_DEVICE);

        set(0, userid);
        set(1, deviceid);
        set(2, token);
        set(3, tokenCreatAt);
        set(4, tokenLastLoginAt);
        set(5, deviceDesc);
        set(6, devicePlatform);
        set(7, deviceOs);
        set(8, deviceBrowser);
    }
}
