/**
 * This class is generated by jOOQ
 */
package com.lrest.server.jooqmodel.tables;


import com.lrest.server.jooqmodel.Gouchehui2_0;
import com.lrest.server.jooqmodel.Keys;
import com.lrest.server.jooqmodel.tables.records.GchCarPreferRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 车款表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GchCarPrefer extends TableImpl<GchCarPreferRecord> {

    private static final long serialVersionUID = 2075028265;

    /**
     * The reference instance of <code>gouchehui2.0.gch_car_prefer</code>
     */
    public static final GchCarPrefer GCH_CAR_PREFER = new GchCarPrefer();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GchCarPreferRecord> getRecordType() {
        return GchCarPreferRecord.class;
    }

    /**
     * The column <code>gouchehui2.0.gch_car_prefer.id</code>. 主键
     */
    public final TableField<GchCarPreferRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "主键");

    /**
     * The column <code>gouchehui2.0.gch_car_prefer.car_id</code>. 访问量
     */
    public final TableField<GchCarPreferRecord, String> CAR_ID = createField("car_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "访问量");

    /**
     * The column <code>gouchehui2.0.gch_car_prefer.car_model_id</code>. 所属车型
     */
    public final TableField<GchCarPreferRecord, String> CAR_MODEL_ID = createField("car_model_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "所属车型");

    /**
     * The column <code>gouchehui2.0.gch_car_prefer.car_name</code>. 名称
     */
    public final TableField<GchCarPreferRecord, String> CAR_NAME = createField("car_name", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "名称");

    /**
     * The column <code>gouchehui2.0.gch_car_prefer.user_id</code>. 描述
     */
    public final TableField<GchCarPreferRecord, String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "描述");

    /**
     * The column <code>gouchehui2.0.gch_car_prefer.createtime</code>. 创建时间
     */
    public final TableField<GchCarPreferRecord, Timestamp> CREATETIME = createField("createtime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");

    /**
     * The column <code>gouchehui2.0.gch_car_prefer.createuser</code>. 创建人
     */
    public final TableField<GchCarPreferRecord, String> CREATEUSER = createField("createuser", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "创建人");

    /**
     * The column <code>gouchehui2.0.gch_car_prefer.isdelete</code>. 是否删除
     */
    public final TableField<GchCarPreferRecord, Integer> ISDELETE = createField("isdelete", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "是否删除");

    /**
     * Create a <code>gouchehui2.0.gch_car_prefer</code> table reference
     */
    public GchCarPrefer() {
        this("gch_car_prefer", null);
    }

    /**
     * Create an aliased <code>gouchehui2.0.gch_car_prefer</code> table reference
     */
    public GchCarPrefer(String alias) {
        this(alias, GCH_CAR_PREFER);
    }

    private GchCarPrefer(String alias, Table<GchCarPreferRecord> aliased) {
        this(alias, aliased, null);
    }

    private GchCarPrefer(String alias, Table<GchCarPreferRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "车款表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Gouchehui2_0.GOUCHEHUI2_0;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GchCarPreferRecord> getPrimaryKey() {
        return Keys.KEY_GCH_CAR_PREFER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GchCarPreferRecord>> getKeys() {
        return Arrays.<UniqueKey<GchCarPreferRecord>>asList(Keys.KEY_GCH_CAR_PREFER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarPrefer as(String alias) {
        return new GchCarPrefer(alias, this);
    }

    /**
     * Rename this table
     */
    public GchCarPrefer rename(String name) {
        return new GchCarPrefer(name, null);
    }
}
