/**
 * This class is generated by jOOQ
 */
package com.lrest.server.jooqmodel.tables;


import com.lrest.server.jooqmodel.Gouchehui2_0;
import com.lrest.server.jooqmodel.Keys;
import com.lrest.server.jooqmodel.tables.records.GchCityRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 4S店所在城市
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GchCity extends TableImpl<GchCityRecord> {

    private static final long serialVersionUID = -769369207;

    /**
     * The reference instance of <code>gouchehui2.0.gch_city</code>
     */
    public static final GchCity GCH_CITY = new GchCity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GchCityRecord> getRecordType() {
        return GchCityRecord.class;
    }

    /**
     * The column <code>gouchehui2.0.gch_city.id</code>. 主键
     */
    public final TableField<GchCityRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "主键");

    /**
     * The column <code>gouchehui2.0.gch_city.province_id</code>. 所属省份
     */
    public final TableField<GchCityRecord, String> PROVINCE_ID = createField("province_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "所属省份");

    /**
     * The column <code>gouchehui2.0.gch_city.city_name</code>. 城市名称
     */
    public final TableField<GchCityRecord, String> CITY_NAME = createField("city_name", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "城市名称");

    /**
     * The column <code>gouchehui2.0.gch_city.createtime</code>. 创建时间
     */
    public final TableField<GchCityRecord, Timestamp> CREATETIME = createField("createtime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");

    /**
     * The column <code>gouchehui2.0.gch_city.createuser</code>. 创建人
     */
    public final TableField<GchCityRecord, String> CREATEUSER = createField("createuser", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "创建人");

    /**
     * The column <code>gouchehui2.0.gch_city.isdelete</code>. 是否删除
     */
    public final TableField<GchCityRecord, Integer> ISDELETE = createField("isdelete", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "是否删除");

    /**
     * The column <code>gouchehui2.0.gch_city.updatetime</code>. 修改时间
     */
    public final TableField<GchCityRecord, Timestamp> UPDATETIME = createField("updatetime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0000-00-00 00:00:00", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "修改时间");

    /**
     * The column <code>gouchehui2.0.gch_city.updateuser</code>. 修改人
     */
    public final TableField<GchCityRecord, String> UPDATEUSER = createField("updateuser", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "修改人");

    /**
     * The column <code>gouchehui2.0.gch_city.status</code>. 是否启用 1启用 0不启用
     */
    public final TableField<GchCityRecord, Byte> STATUS = createField("status", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.TINYINT)), this, "是否启用 1启用 0不启用");

    /**
     * Create a <code>gouchehui2.0.gch_city</code> table reference
     */
    public GchCity() {
        this("gch_city", null);
    }

    /**
     * Create an aliased <code>gouchehui2.0.gch_city</code> table reference
     */
    public GchCity(String alias) {
        this(alias, GCH_CITY);
    }

    private GchCity(String alias, Table<GchCityRecord> aliased) {
        this(alias, aliased, null);
    }

    private GchCity(String alias, Table<GchCityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "4S店所在城市");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Gouchehui2_0.GOUCHEHUI2_0;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GchCityRecord> getPrimaryKey() {
        return Keys.KEY_GCH_CITY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GchCityRecord>> getKeys() {
        return Arrays.<UniqueKey<GchCityRecord>>asList(Keys.KEY_GCH_CITY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCity as(String alias) {
        return new GchCity(alias, this);
    }

    /**
     * Rename this table
     */
    public GchCity rename(String name) {
        return new GchCity(name, null);
    }
}
