/**
 * This class is generated by jOOQ
 */
package com.lrest.server.jooqmodel.tables;


import com.lrest.server.jooqmodel.Gouchehui2_0;
import com.lrest.server.jooqmodel.Keys;
import com.lrest.server.jooqmodel.tables.records.GchCarModelPreferRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 4s用户车型喜好表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GchCarModelPrefer extends TableImpl<GchCarModelPreferRecord> {

    private static final long serialVersionUID = 1882670449;

    /**
     * The reference instance of <code>gouchehui2.0.gch_car_model_prefer</code>
     */
    public static final GchCarModelPrefer GCH_CAR_MODEL_PREFER = new GchCarModelPrefer();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GchCarModelPreferRecord> getRecordType() {
        return GchCarModelPreferRecord.class;
    }

    /**
     * The column <code>gouchehui2.0.gch_car_model_prefer.id</code>. 主键
     */
    public final TableField<GchCarModelPreferRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "主键");

    /**
     * The column <code>gouchehui2.0.gch_car_model_prefer.brand_id</code>. 所属品牌
     */
    public final TableField<GchCarModelPreferRecord, String> BRAND_ID = createField("brand_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "所属品牌");

    /**
     * The column <code>gouchehui2.0.gch_car_model_prefer.car_model_id</code>. 车型ID
     */
    public final TableField<GchCarModelPreferRecord, String> CAR_MODEL_ID = createField("car_model_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "车型ID");

    /**
     * The column <code>gouchehui2.0.gch_car_model_prefer.user_id</code>. 访问量
     */
    public final TableField<GchCarModelPreferRecord, String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "访问量");

    /**
     * The column <code>gouchehui2.0.gch_car_model_prefer.car_model_name</code>. 名称
     */
    public final TableField<GchCarModelPreferRecord, String> CAR_MODEL_NAME = createField("car_model_name", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "名称");

    /**
     * The column <code>gouchehui2.0.gch_car_model_prefer.createtime</code>. 创建时间
     */
    public final TableField<GchCarModelPreferRecord, Timestamp> CREATETIME = createField("createtime", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");

    /**
     * The column <code>gouchehui2.0.gch_car_model_prefer.createuser</code>. 创建人
     */
    public final TableField<GchCarModelPreferRecord, String> CREATEUSER = createField("createuser", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "创建人");

    /**
     * The column <code>gouchehui2.0.gch_car_model_prefer.isdelete</code>. 是否删除
     */
    public final TableField<GchCarModelPreferRecord, Integer> ISDELETE = createField("isdelete", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "是否删除");

    /**
     * The column <code>gouchehui2.0.gch_car_model_prefer.updatetime</code>. 修改时间
     */
    public final TableField<GchCarModelPreferRecord, Timestamp> UPDATETIME = createField("updatetime", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.inline("0000-00-00 00:00:00", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "修改时间");

    /**
     * The column <code>gouchehui2.0.gch_car_model_prefer.updateuser</code>. 修改人
     */
    public final TableField<GchCarModelPreferRecord, String> UPDATEUSER = createField("updateuser", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "修改人");

    /**
     * Create a <code>gouchehui2.0.gch_car_model_prefer</code> table reference
     */
    public GchCarModelPrefer() {
        this("gch_car_model_prefer", null);
    }

    /**
     * Create an aliased <code>gouchehui2.0.gch_car_model_prefer</code> table reference
     */
    public GchCarModelPrefer(String alias) {
        this(alias, GCH_CAR_MODEL_PREFER);
    }

    private GchCarModelPrefer(String alias, Table<GchCarModelPreferRecord> aliased) {
        this(alias, aliased, null);
    }

    private GchCarModelPrefer(String alias, Table<GchCarModelPreferRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "4s用户车型喜好表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Gouchehui2_0.GOUCHEHUI2_0;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GchCarModelPreferRecord> getPrimaryKey() {
        return Keys.KEY_GCH_CAR_MODEL_PREFER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GchCarModelPreferRecord>> getKeys() {
        return Arrays.<UniqueKey<GchCarModelPreferRecord>>asList(Keys.KEY_GCH_CAR_MODEL_PREFER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchCarModelPrefer as(String alias) {
        return new GchCarModelPrefer(alias, this);
    }

    /**
     * Rename this table
     */
    public GchCarModelPrefer rename(String name) {
        return new GchCarModelPrefer(name, null);
    }
}
