/**
 * This class is generated by jOOQ
 */
package com.lrest.server.jooqmodel.tables;


import com.lrest.server.jooqmodel.Gouchehui2_0;
import com.lrest.server.jooqmodel.Keys;
import com.lrest.server.jooqmodel.tables.records.GchScoreExchangeRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GchScoreExchange extends TableImpl<GchScoreExchangeRecord> {

    private static final long serialVersionUID = 687758448;

    /**
     * The reference instance of <code>gouchehui2.0.gch_score_exchange</code>
     */
    public static final GchScoreExchange GCH_SCORE_EXCHANGE = new GchScoreExchange();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GchScoreExchangeRecord> getRecordType() {
        return GchScoreExchangeRecord.class;
    }

    /**
     * The column <code>gouchehui2.0.gch_score_exchange.id</code>. id主键
     */
    public final TableField<GchScoreExchangeRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "id主键");

    /**
     * The column <code>gouchehui2.0.gch_score_exchange.out_trade_no</code>. 订单号
     */
    public final TableField<GchScoreExchangeRecord, String> OUT_TRADE_NO = createField("out_trade_no", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "订单号");

    /**
     * The column <code>gouchehui2.0.gch_score_exchange.user_id</code>. 用户id
     */
    public final TableField<GchScoreExchangeRecord, String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "用户id");

    /**
     * The column <code>gouchehui2.0.gch_score_exchange.role</code>.
     */
    public final TableField<GchScoreExchangeRecord, Byte> ROLE = createField("role", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>gouchehui2.0.gch_score_exchange.telphone</code>. 兑换人的手机号
     */
    public final TableField<GchScoreExchangeRecord, String> TELPHONE = createField("telphone", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "兑换人的手机号");

    /**
     * The column <code>gouchehui2.0.gch_score_exchange.goods_id</code>. 积分商品id
     */
    public final TableField<GchScoreExchangeRecord, String> GOODS_ID = createField("goods_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "积分商品id");

    /**
     * The column <code>gouchehui2.0.gch_score_exchange.goods_name</code>. 积分商品名称
     */
    public final TableField<GchScoreExchangeRecord, String> GOODS_NAME = createField("goods_name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "积分商品名称");

    /**
     * The column <code>gouchehui2.0.gch_score_exchange.score_value</code>. 消耗的积分值
     */
    public final TableField<GchScoreExchangeRecord, Integer> SCORE_VALUE = createField("score_value", org.jooq.impl.SQLDataType.INTEGER, this, "消耗的积分值");

    /**
     * The column <code>gouchehui2.0.gch_score_exchange.address_id</code>. 收货地址
     */
    public final TableField<GchScoreExchangeRecord, String> ADDRESS_ID = createField("address_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "收货地址");

    /**
     * The column <code>gouchehui2.0.gch_score_exchange.status</code>. 兑换状态：1未兑换，2已兑换
     */
    public final TableField<GchScoreExchangeRecord, Byte> STATUS = createField("status", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.TINYINT)), this, "兑换状态：1未兑换，2已兑换");

    /**
     * The column <code>gouchehui2.0.gch_score_exchange.cus_name</code>. 操作人姓名
     */
    public final TableField<GchScoreExchangeRecord, String> CUS_NAME = createField("cus_name", org.jooq.impl.SQLDataType.VARCHAR.length(32).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "操作人姓名");

    /**
     * The column <code>gouchehui2.0.gch_score_exchange.createtime</code>. 创建时间
     */
    public final TableField<GchScoreExchangeRecord, Timestamp> CREATETIME = createField("createtime", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");

    /**
     * The column <code>gouchehui2.0.gch_score_exchange.createuser</code>. 创建人
     */
    public final TableField<GchScoreExchangeRecord, String> CREATEUSER = createField("createuser", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "创建人");

    /**
     * The column <code>gouchehui2.0.gch_score_exchange.isdelete</code>.
     */
    public final TableField<GchScoreExchangeRecord, Integer> ISDELETE = createField("isdelete", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>gouchehui2.0.gch_score_exchange.updatetime</code>. 修改时间
     */
    public final TableField<GchScoreExchangeRecord, Timestamp> UPDATETIME = createField("updatetime", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.inline("0000-00-00 00:00:00", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "修改时间");

    /**
     * The column <code>gouchehui2.0.gch_score_exchange.updateuser</code>. 修改人
     */
    public final TableField<GchScoreExchangeRecord, String> UPDATEUSER = createField("updateuser", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "修改人");

    /**
     * Create a <code>gouchehui2.0.gch_score_exchange</code> table reference
     */
    public GchScoreExchange() {
        this("gch_score_exchange", null);
    }

    /**
     * Create an aliased <code>gouchehui2.0.gch_score_exchange</code> table reference
     */
    public GchScoreExchange(String alias) {
        this(alias, GCH_SCORE_EXCHANGE);
    }

    private GchScoreExchange(String alias, Table<GchScoreExchangeRecord> aliased) {
        this(alias, aliased, null);
    }

    private GchScoreExchange(String alias, Table<GchScoreExchangeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Gouchehui2_0.GOUCHEHUI2_0;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GchScoreExchangeRecord> getPrimaryKey() {
        return Keys.KEY_GCH_SCORE_EXCHANGE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GchScoreExchangeRecord>> getKeys() {
        return Arrays.<UniqueKey<GchScoreExchangeRecord>>asList(Keys.KEY_GCH_SCORE_EXCHANGE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchScoreExchange as(String alias) {
        return new GchScoreExchange(alias, this);
    }

    /**
     * Rename this table
     */
    public GchScoreExchange rename(String name) {
        return new GchScoreExchange(name, null);
    }
}
