/**
 * This class is generated by jOOQ
 */
package com.lrest.server.jooqmodel.tables;


import com.lrest.server.jooqmodel.Gouchehui2_0;
import com.lrest.server.jooqmodel.Keys;
import com.lrest.server.jooqmodel.tables.records.GchSpecialPriceCarRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 特价车
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GchSpecialPriceCar extends TableImpl<GchSpecialPriceCarRecord> {

    private static final long serialVersionUID = 1057636449;

    /**
     * The reference instance of <code>gouchehui2.0.gch_special_price_car</code>
     */
    public static final GchSpecialPriceCar GCH_SPECIAL_PRICE_CAR = new GchSpecialPriceCar();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GchSpecialPriceCarRecord> getRecordType() {
        return GchSpecialPriceCarRecord.class;
    }

    /**
     * The column <code>gouchehui2.0.gch_special_price_car.id</code>. 主键
     */
    public final TableField<GchSpecialPriceCarRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "主键");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car.user_id</code>. 关联用户ID
     */
    public final TableField<GchSpecialPriceCarRecord, String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "关联用户ID");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car.interior_color_id</code>. 内饰颜色ID
     */
    public final TableField<GchSpecialPriceCarRecord, String> INTERIOR_COLOR_ID = createField("interior_color_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "内饰颜色ID");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car.exterior_color_id</code>. 外观颜色ID
     */
    public final TableField<GchSpecialPriceCarRecord, String> EXTERIOR_COLOR_ID = createField("exterior_color_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "外观颜色ID");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car.car_image</code>. 车款图片
     */
    public final TableField<GchSpecialPriceCarRecord, String> CAR_IMAGE = createField("car_image", org.jooq.impl.SQLDataType.VARCHAR.length(500).nullable(false), this, "车款图片");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car.client</code>. 客户端(1:pc,2:手机web端)
     */
    public final TableField<GchSpecialPriceCarRecord, Integer> CLIENT = createField("client", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.INTEGER)), this, "客户端(1:pc,2:手机web端)");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car.car_id</code>. 汽车ID
     */
    public final TableField<GchSpecialPriceCarRecord, String> CAR_ID = createField("car_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "汽车ID");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car.price</code>. 价格
     */
    public final TableField<GchSpecialPriceCarRecord, Integer> PRICE = createField("price", org.jooq.impl.SQLDataType.INTEGER, this, "价格");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car.special_price</code>. 特价
     */
    public final TableField<GchSpecialPriceCarRecord, Integer> SPECIAL_PRICE = createField("special_price", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "特价");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car.start_date</code>. 开始时间
     */
    public final TableField<GchSpecialPriceCarRecord, Timestamp> START_DATE = createField("start_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "开始时间");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car.end_date</code>. 结束时间
     */
    public final TableField<GchSpecialPriceCarRecord, Timestamp> END_DATE = createField("end_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "结束时间");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car.number</code>. 活动数量
     */
    public final TableField<GchSpecialPriceCarRecord, Integer> NUMBER = createField("number", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "活动数量");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car.status</code>. 特价车状态（1：审核中，2：未开始，3：在售，4：停售，5：过期，6：审核失败）
     */
    public final TableField<GchSpecialPriceCarRecord, Byte> STATUS = createField("status", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.TINYINT)), this, "特价车状态（1：审核中，2：未开始，3：在售，4：停售，5：过期，6：审核失败）");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car.remark</code>. 备注(审核不通过）
     */
    public final TableField<GchSpecialPriceCarRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "备注(审核不通过）");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car.description</code>. 活动说明
     */
    public final TableField<GchSpecialPriceCarRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "活动说明");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car.attention_count</code>. 关注度
     */
    public final TableField<GchSpecialPriceCarRecord, Integer> ATTENTION_COUNT = createField("attention_count", org.jooq.impl.SQLDataType.INTEGER, this, "关注度");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car.createtime</code>. 创建时间
     */
    public final TableField<GchSpecialPriceCarRecord, Timestamp> CREATETIME = createField("createtime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car.createuser</code>. 创建人
     */
    public final TableField<GchSpecialPriceCarRecord, String> CREATEUSER = createField("createuser", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "创建人");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car.isdelete</code>. 是否删除
     */
    public final TableField<GchSpecialPriceCarRecord, Integer> ISDELETE = createField("isdelete", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "是否删除");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car.updateuser</code>. 修改人
     */
    public final TableField<GchSpecialPriceCarRecord, String> UPDATEUSER = createField("updateuser", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "修改人");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car.updatetime</code>. 修改时间
     */
    public final TableField<GchSpecialPriceCarRecord, Timestamp> UPDATETIME = createField("updatetime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0000-00-00 00:00:00", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "修改时间");

    /**
     * Create a <code>gouchehui2.0.gch_special_price_car</code> table reference
     */
    public GchSpecialPriceCar() {
        this("gch_special_price_car", null);
    }

    /**
     * Create an aliased <code>gouchehui2.0.gch_special_price_car</code> table reference
     */
    public GchSpecialPriceCar(String alias) {
        this(alias, GCH_SPECIAL_PRICE_CAR);
    }

    private GchSpecialPriceCar(String alias, Table<GchSpecialPriceCarRecord> aliased) {
        this(alias, aliased, null);
    }

    private GchSpecialPriceCar(String alias, Table<GchSpecialPriceCarRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "特价车");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Gouchehui2_0.GOUCHEHUI2_0;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GchSpecialPriceCarRecord> getPrimaryKey() {
        return Keys.KEY_GCH_SPECIAL_PRICE_CAR_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GchSpecialPriceCarRecord>> getKeys() {
        return Arrays.<UniqueKey<GchSpecialPriceCarRecord>>asList(Keys.KEY_GCH_SPECIAL_PRICE_CAR_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchSpecialPriceCar as(String alias) {
        return new GchSpecialPriceCar(alias, this);
    }

    /**
     * Rename this table
     */
    public GchSpecialPriceCar rename(String name) {
        return new GchSpecialPriceCar(name, null);
    }
}
