/**
 * This class is generated by jOOQ
 */
package com.lrest.server.jooqmodel.tables;


import com.lrest.server.jooqmodel.Gouchehui2_0;
import com.lrest.server.jooqmodel.Keys;
import com.lrest.server.jooqmodel.tables.records.GchSalesAreaRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 销售区域表（底价车、特价车）
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GchSalesArea extends TableImpl<GchSalesAreaRecord> {

    private static final long serialVersionUID = 1530820928;

    /**
     * The reference instance of <code>gouchehui2.0.gch_sales_area</code>
     */
    public static final GchSalesArea GCH_SALES_AREA = new GchSalesArea();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GchSalesAreaRecord> getRecordType() {
        return GchSalesAreaRecord.class;
    }

    /**
     * The column <code>gouchehui2.0.gch_sales_area.id</code>. 主键
     */
    public final TableField<GchSalesAreaRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "主键");

    /**
     * The column <code>gouchehui2.0.gch_sales_area.sales_area_name</code>. 销售区域名称
     */
    public final TableField<GchSalesAreaRecord, String> SALES_AREA_NAME = createField("sales_area_name", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "销售区域名称");

    /**
     * The column <code>gouchehui2.0.gch_sales_area.sales_area_level</code>. 销售区域权重 1、全国 2、省份 3、城市
     */
    public final TableField<GchSalesAreaRecord, Integer> SALES_AREA_LEVEL = createField("sales_area_level", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "销售区域权重 1、全国 2、省份 3、城市");

    /**
     * The column <code>gouchehui2.0.gch_sales_area.car_price_id</code>. 低价车id
     */
    public final TableField<GchSalesAreaRecord, String> CAR_PRICE_ID = createField("car_price_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "低价车id");

    /**
     * The column <code>gouchehui2.0.gch_sales_area.car_special_id</code>. 特价车ID
     */
    public final TableField<GchSalesAreaRecord, String> CAR_SPECIAL_ID = createField("car_special_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "特价车ID");

    /**
     * The column <code>gouchehui2.0.gch_sales_area.type</code>. 销售区域类别1 底价车，2特价车
     */
    public final TableField<GchSalesAreaRecord, Integer> TYPE = createField("type", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "销售区域类别1 底价车，2特价车");

    /**
     * The column <code>gouchehui2.0.gch_sales_area.createtime</code>. 创建时间
     */
    public final TableField<GchSalesAreaRecord, Timestamp> CREATETIME = createField("createtime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");

    /**
     * The column <code>gouchehui2.0.gch_sales_area.createuser</code>. 创建人
     */
    public final TableField<GchSalesAreaRecord, String> CREATEUSER = createField("createuser", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "创建人");

    /**
     * The column <code>gouchehui2.0.gch_sales_area.isdelete</code>. 是否删除
     */
    public final TableField<GchSalesAreaRecord, Integer> ISDELETE = createField("isdelete", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "是否删除");

    /**
     * The column <code>gouchehui2.0.gch_sales_area.updatetime</code>. 修改时间
     */
    public final TableField<GchSalesAreaRecord, Timestamp> UPDATETIME = createField("updatetime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0000-00-00 00:00:00", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "修改时间");

    /**
     * The column <code>gouchehui2.0.gch_sales_area.updateuser</code>. 修改人
     */
    public final TableField<GchSalesAreaRecord, String> UPDATEUSER = createField("updateuser", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "修改人");

    /**
     * Create a <code>gouchehui2.0.gch_sales_area</code> table reference
     */
    public GchSalesArea() {
        this("gch_sales_area", null);
    }

    /**
     * Create an aliased <code>gouchehui2.0.gch_sales_area</code> table reference
     */
    public GchSalesArea(String alias) {
        this(alias, GCH_SALES_AREA);
    }

    private GchSalesArea(String alias, Table<GchSalesAreaRecord> aliased) {
        this(alias, aliased, null);
    }

    private GchSalesArea(String alias, Table<GchSalesAreaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "销售区域表（底价车、特价车）");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Gouchehui2_0.GOUCHEHUI2_0;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GchSalesAreaRecord> getPrimaryKey() {
        return Keys.KEY_GCH_SALES_AREA_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GchSalesAreaRecord>> getKeys() {
        return Arrays.<UniqueKey<GchSalesAreaRecord>>asList(Keys.KEY_GCH_SALES_AREA_PRIMARY, Keys.KEY_GCH_SALES_AREA_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchSalesArea as(String alias) {
        return new GchSalesArea(alias, this);
    }

    /**
     * Rename this table
     */
    public GchSalesArea rename(String name) {
        return new GchSalesArea(name, null);
    }
}
