/**
 * This class is generated by jOOQ
 */
package com.lrest.server.jooqmodel.tables;


import com.lrest.server.jooqmodel.Gouchehui2_0;
import com.lrest.server.jooqmodel.Keys;
import com.lrest.server.jooqmodel.tables.records.GchSpecialPriceCarTrendRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 特价车
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GchSpecialPriceCarTrend extends TableImpl<GchSpecialPriceCarTrendRecord> {

    private static final long serialVersionUID = -276462824;

    /**
     * The reference instance of <code>gouchehui2.0.gch_special_price_car_trend</code>
     */
    public static final GchSpecialPriceCarTrend GCH_SPECIAL_PRICE_CAR_TREND = new GchSpecialPriceCarTrend();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GchSpecialPriceCarTrendRecord> getRecordType() {
        return GchSpecialPriceCarTrendRecord.class;
    }

    /**
     * The column <code>gouchehui2.0.gch_special_price_car_trend.id</code>. 主键
     */
    public final TableField<GchSpecialPriceCarTrendRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "主键");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car_trend.special_price_car</code>. gch_special_price_car表的ID
     */
    public final TableField<GchSpecialPriceCarTrendRecord, String> SPECIAL_PRICE_CAR = createField("special_price_car", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "gch_special_price_car表的ID");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car_trend.user_id</code>. 关联用户ID
     */
    public final TableField<GchSpecialPriceCarTrendRecord, String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "关联用户ID");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car_trend.interior_color_id</code>. 内饰颜色ID
     */
    public final TableField<GchSpecialPriceCarTrendRecord, String> INTERIOR_COLOR_ID = createField("interior_color_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "内饰颜色ID");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car_trend.exterior_color_id</code>. 外观颜色ID
     */
    public final TableField<GchSpecialPriceCarTrendRecord, String> EXTERIOR_COLOR_ID = createField("exterior_color_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "外观颜色ID");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car_trend.car_image</code>. 车款图片
     */
    public final TableField<GchSpecialPriceCarTrendRecord, String> CAR_IMAGE = createField("car_image", org.jooq.impl.SQLDataType.VARCHAR.length(500).nullable(false), this, "车款图片");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car_trend.car_id</code>. 汽车ID
     */
    public final TableField<GchSpecialPriceCarTrendRecord, String> CAR_ID = createField("car_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "汽车ID");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car_trend.price</code>. 价格
     */
    public final TableField<GchSpecialPriceCarTrendRecord, Integer> PRICE = createField("price", org.jooq.impl.SQLDataType.INTEGER, this, "价格");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car_trend.special_price</code>. 特价
     */
    public final TableField<GchSpecialPriceCarTrendRecord, Integer> SPECIAL_PRICE = createField("special_price", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "特价");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car_trend.start_date</code>. 开始时间
     */
    public final TableField<GchSpecialPriceCarTrendRecord, Timestamp> START_DATE = createField("start_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "开始时间");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car_trend.end_date</code>. 结束时间
     */
    public final TableField<GchSpecialPriceCarTrendRecord, Timestamp> END_DATE = createField("end_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "结束时间");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car_trend.number</code>. 活动数量
     */
    public final TableField<GchSpecialPriceCarTrendRecord, Integer> NUMBER = createField("number", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "活动数量");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car_trend.status</code>. 特价车状态（1：审核中，2：未开始，3：在售，4：停售，5：过期，6：审核失败）
     */
    public final TableField<GchSpecialPriceCarTrendRecord, Byte> STATUS = createField("status", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.TINYINT)), this, "特价车状态（1：审核中，2：未开始，3：在售，4：停售，5：过期，6：审核失败）");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car_trend.description</code>. 活动说明
     */
    public final TableField<GchSpecialPriceCarTrendRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "活动说明");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car_trend.createtime</code>. 创建时间
     */
    public final TableField<GchSpecialPriceCarTrendRecord, Timestamp> CREATETIME = createField("createtime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");

    /**
     * The column <code>gouchehui2.0.gch_special_price_car_trend.createuser</code>. 创建人
     */
    public final TableField<GchSpecialPriceCarTrendRecord, String> CREATEUSER = createField("createuser", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "创建人");

    /**
     * Create a <code>gouchehui2.0.gch_special_price_car_trend</code> table reference
     */
    public GchSpecialPriceCarTrend() {
        this("gch_special_price_car_trend", null);
    }

    /**
     * Create an aliased <code>gouchehui2.0.gch_special_price_car_trend</code> table reference
     */
    public GchSpecialPriceCarTrend(String alias) {
        this(alias, GCH_SPECIAL_PRICE_CAR_TREND);
    }

    private GchSpecialPriceCarTrend(String alias, Table<GchSpecialPriceCarTrendRecord> aliased) {
        this(alias, aliased, null);
    }

    private GchSpecialPriceCarTrend(String alias, Table<GchSpecialPriceCarTrendRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "特价车");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Gouchehui2_0.GOUCHEHUI2_0;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GchSpecialPriceCarTrendRecord> getPrimaryKey() {
        return Keys.KEY_GCH_SPECIAL_PRICE_CAR_TREND_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GchSpecialPriceCarTrendRecord>> getKeys() {
        return Arrays.<UniqueKey<GchSpecialPriceCarTrendRecord>>asList(Keys.KEY_GCH_SPECIAL_PRICE_CAR_TREND_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchSpecialPriceCarTrend as(String alias) {
        return new GchSpecialPriceCarTrend(alias, this);
    }

    /**
     * Rename this table
     */
    public GchSpecialPriceCarTrend rename(String name) {
        return new GchSpecialPriceCarTrend(name, null);
    }
}
