/**
 * This class is generated by jOOQ
 */
package com.lrest.server.jooqmodel.tables;


import com.lrest.server.jooqmodel.Gouchehui2_0;
import com.lrest.server.jooqmodel.Keys;
import com.lrest.server.jooqmodel.tables.records.GchUserGeneralRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 用户表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GchUserGeneral extends TableImpl<GchUserGeneralRecord> {

    private static final long serialVersionUID = -2086281227;

    /**
     * The reference instance of <code>gouchehui2.0.gch_user_general</code>
     */
    public static final GchUserGeneral GCH_USER_GENERAL = new GchUserGeneral();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GchUserGeneralRecord> getRecordType() {
        return GchUserGeneralRecord.class;
    }

    /**
     * The column <code>gouchehui2.0.gch_user_general.id</code>. 主键
     */
    public final TableField<GchUserGeneralRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "主键");

    /**
     * The column <code>gouchehui2.0.gch_user_general.user_name</code>. 登录名
     */
    public final TableField<GchUserGeneralRecord, String> USER_NAME = createField("user_name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "登录名");

    /**
     * The column <code>gouchehui2.0.gch_user_general.password</code>. 登陆密码(MD5)
     */
    public final TableField<GchUserGeneralRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "登陆密码(MD5)");

    /**
     * The column <code>gouchehui2.0.gch_user_general.role</code>. 身份1、普通用户 2、4S店会员(关联到4S店自定管理4S店主键) 3、经销商
     */
    public final TableField<GchUserGeneralRecord, Integer> ROLE = createField("role", org.jooq.impl.SQLDataType.INTEGER, this, "身份1、普通用户 2、4S店会员(关联到4S店自定管理4S店主键) 3、经销商");

    /**
     * The column <code>gouchehui2.0.gch_user_general.tel</code>. 电话
     */
    public final TableField<GchUserGeneralRecord, String> TEL = createField("tel", org.jooq.impl.SQLDataType.VARCHAR.length(15), this, "电话");

    /**
     * The column <code>gouchehui2.0.gch_user_general.email</code>. 邮箱
     */
    public final TableField<GchUserGeneralRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "邮箱");

    /**
     * The column <code>gouchehui2.0.gch_user_general.head_url</code>. 头像
     */
    public final TableField<GchUserGeneralRecord, String> HEAD_URL = createField("head_url", org.jooq.impl.SQLDataType.VARCHAR.length(240), this, "头像");

    /**
     * The column <code>gouchehui2.0.gch_user_general.name</code>.
     */
    public final TableField<GchUserGeneralRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

    /**
     * The column <code>gouchehui2.0.gch_user_general.nick</code>. 真实姓名
     */
    public final TableField<GchUserGeneralRecord, String> NICK = createField("nick", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "真实姓名");

    /**
     * The column <code>gouchehui2.0.gch_user_general.sex</code>. 性别 0、男 1、女
     */
    public final TableField<GchUserGeneralRecord, Integer> SEX = createField("sex", org.jooq.impl.SQLDataType.INTEGER, this, "性别 0、男 1、女");

    /**
     * The column <code>gouchehui2.0.gch_user_general.birthday</code>. 生日
     */
    public final TableField<GchUserGeneralRecord, String> BIRTHDAY = createField("birthday", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "生日");

    /**
     * The column <code>gouchehui2.0.gch_user_general.province_id</code>. 所在地-省份
     */
    public final TableField<GchUserGeneralRecord, String> PROVINCE_ID = createField("province_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "所在地-省份");

    /**
     * The column <code>gouchehui2.0.gch_user_general.city_id</code>. 所在地-城市
     */
    public final TableField<GchUserGeneralRecord, String> CITY_ID = createField("city_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "所在地-城市");

    /**
     * The column <code>gouchehui2.0.gch_user_general.district_id</code>. 区ID
     */
    public final TableField<GchUserGeneralRecord, String> DISTRICT_ID = createField("district_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "区ID");

    /**
     * The column <code>gouchehui2.0.gch_user_general.address</code>. 详细地址
     */
    public final TableField<GchUserGeneralRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR.length(255).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "详细地址");

    /**
     * The column <code>gouchehui2.0.gch_user_general.postcode</code>. 邮编
     */
    public final TableField<GchUserGeneralRecord, String> POSTCODE = createField("postcode", org.jooq.impl.SQLDataType.VARCHAR.length(11), this, "邮编");

    /**
     * The column <code>gouchehui2.0.gch_user_general.status</code>. 用户状态（0，锁定；1，正常）
     */
    public final TableField<GchUserGeneralRecord, Short> STATUS = createField("status", org.jooq.impl.SQLDataType.SMALLINT, this, "用户状态（0，锁定；1，正常）");

    /**
     * The column <code>gouchehui2.0.gch_user_general.my_num</code>. 我的邀请码
     */
    public final TableField<GchUserGeneralRecord, String> MY_NUM = createField("my_num", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "我的邀请码");

    /**
     * The column <code>gouchehui2.0.gch_user_general.binding_num</code>. 绑定邀请码
     */
    public final TableField<GchUserGeneralRecord, String> BINDING_NUM = createField("binding_num", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "绑定邀请码");

    /**
     * The column <code>gouchehui2.0.gch_user_general.total_coin</code>. 车币
     */
    public final TableField<GchUserGeneralRecord, Integer> TOTAL_COIN = createField("total_coin", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "车币");

    /**
     * The column <code>gouchehui2.0.gch_user_general.total_jifen</code>. 用户积分
     */
    public final TableField<GchUserGeneralRecord, Integer> TOTAL_JIFEN = createField("total_jifen", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "用户积分");

    /**
     * The column <code>gouchehui2.0.gch_user_general.balance</code>. 余额
     */
    public final TableField<GchUserGeneralRecord, String> BALANCE = createField("balance", org.jooq.impl.SQLDataType.VARCHAR.length(10), this, "余额");

    /**
     * The column <code>gouchehui2.0.gch_user_general.jifen_sign</code>.
     */
    public final TableField<GchUserGeneralRecord, String> JIFEN_SIGN = createField("jifen_sign", org.jooq.impl.SQLDataType.VARCHAR.length(2).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>gouchehui2.0.gch_user_general.wx_open_id</code>. 微信开放用户ID
     */
    public final TableField<GchUserGeneralRecord, String> WX_OPEN_ID = createField("wx_open_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "微信开放用户ID");

    /**
     * The column <code>gouchehui2.0.gch_user_general.qq_open_id</code>. QQ互联用户open_id
     */
    public final TableField<GchUserGeneralRecord, String> QQ_OPEN_ID = createField("qq_open_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "QQ互联用户open_id");

    /**
     * The column <code>gouchehui2.0.gch_user_general.logintime</code>.
     */
    public final TableField<GchUserGeneralRecord, String> LOGINTIME = createField("logintime", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

    /**
     * The column <code>gouchehui2.0.gch_user_general.loginip</code>.
     */
    public final TableField<GchUserGeneralRecord, String> LOGINIP = createField("loginip", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

    /**
     * The column <code>gouchehui2.0.gch_user_general.remark</code>. 备注
     */
    public final TableField<GchUserGeneralRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.CLOB, this, "备注");

    /**
     * The column <code>gouchehui2.0.gch_user_general.createtime</code>. 创建时间
     */
    public final TableField<GchUserGeneralRecord, Timestamp> CREATETIME = createField("createtime", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");

    /**
     * The column <code>gouchehui2.0.gch_user_general.createuser</code>.
     */
    public final TableField<GchUserGeneralRecord, String> CREATEUSER = createField("createuser", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

    /**
     * The column <code>gouchehui2.0.gch_user_general.isdelete</code>. 是否删除
     */
    public final TableField<GchUserGeneralRecord, Integer> ISDELETE = createField("isdelete", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "是否删除");

    /**
     * The column <code>gouchehui2.0.gch_user_general.updatetime</code>. 修改时间
     */
    public final TableField<GchUserGeneralRecord, Timestamp> UPDATETIME = createField("updatetime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0000-00-00 00:00:00", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "修改时间");

    /**
     * The column <code>gouchehui2.0.gch_user_general.updateuser</code>.
     */
    public final TableField<GchUserGeneralRecord, String> UPDATEUSER = createField("updateuser", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

    /**
     * The column <code>gouchehui2.0.gch_user_general.activity_attention_num</code>. 活动中通过该用户关注我们公众号的总数
     */
    public final TableField<GchUserGeneralRecord, Integer> ACTIVITY_ATTENTION_NUM = createField("activity_attention_num", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "活动中通过该用户关注我们公众号的总数");

    /**
     * The column <code>gouchehui2.0.gch_user_general.activity_register_num</code>. 通过活动注册的总数
     */
    public final TableField<GchUserGeneralRecord, Integer> ACTIVITY_REGISTER_NUM = createField("activity_register_num", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "通过活动注册的总数");

    /**
     * The column <code>gouchehui2.0.gch_user_general.buy_car_num</code>. 通过该用户买车的用户的总数
     */
    public final TableField<GchUserGeneralRecord, Integer> BUY_CAR_NUM = createField("buy_car_num", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "通过该用户买车的用户的总数");

    /**
     * Create a <code>gouchehui2.0.gch_user_general</code> table reference
     */
    public GchUserGeneral() {
        this("gch_user_general", null);
    }

    /**
     * Create an aliased <code>gouchehui2.0.gch_user_general</code> table reference
     */
    public GchUserGeneral(String alias) {
        this(alias, GCH_USER_GENERAL);
    }

    private GchUserGeneral(String alias, Table<GchUserGeneralRecord> aliased) {
        this(alias, aliased, null);
    }

    private GchUserGeneral(String alias, Table<GchUserGeneralRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "用户表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Gouchehui2_0.GOUCHEHUI2_0;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GchUserGeneralRecord> getPrimaryKey() {
        return Keys.KEY_GCH_USER_GENERAL_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GchUserGeneralRecord>> getKeys() {
        return Arrays.<UniqueKey<GchUserGeneralRecord>>asList(Keys.KEY_GCH_USER_GENERAL_PRIMARY, Keys.KEY_GCH_USER_GENERAL_WX_OPEN_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchUserGeneral as(String alias) {
        return new GchUserGeneral(alias, this);
    }

    /**
     * Rename this table
     */
    public GchUserGeneral rename(String name) {
        return new GchUserGeneral(name, null);
    }
}
