/**
 * This class is generated by jOOQ
 */
package com.lrest.server.jooqmodel.tables;


import com.lrest.server.jooqmodel.Gouchehui2_0;
import com.lrest.server.jooqmodel.Keys;
import com.lrest.server.jooqmodel.tables.records.GchUserAttentionCarModelRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 用户关注车型表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GchUserAttentionCarModel extends TableImpl<GchUserAttentionCarModelRecord> {

    private static final long serialVersionUID = 1929209100;

    /**
     * The reference instance of <code>gouchehui2.0.gch_user_attention_car_model</code>
     */
    public static final GchUserAttentionCarModel GCH_USER_ATTENTION_CAR_MODEL = new GchUserAttentionCarModel();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GchUserAttentionCarModelRecord> getRecordType() {
        return GchUserAttentionCarModelRecord.class;
    }

    /**
     * The column <code>gouchehui2.0.gch_user_attention_car_model.id</code>. 主键
     */
    public final TableField<GchUserAttentionCarModelRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "主键");

    /**
     * The column <code>gouchehui2.0.gch_user_attention_car_model.user_id</code>. 关注用户
     */
    public final TableField<GchUserAttentionCarModelRecord, String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "关注用户");

    /**
     * The column <code>gouchehui2.0.gch_user_attention_car_model.car_model_id</code>. 所属车型
     */
    public final TableField<GchUserAttentionCarModelRecord, String> CAR_MODEL_ID = createField("car_model_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "所属车型");

    /**
     * The column <code>gouchehui2.0.gch_user_attention_car_model.createtime</code>. 创建时间(关注时间)
     */
    public final TableField<GchUserAttentionCarModelRecord, Timestamp> CREATETIME = createField("createtime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间(关注时间)");

    /**
     * The column <code>gouchehui2.0.gch_user_attention_car_model.createuser</code>. 创建人
     */
    public final TableField<GchUserAttentionCarModelRecord, String> CREATEUSER = createField("createuser", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "创建人");

    /**
     * The column <code>gouchehui2.0.gch_user_attention_car_model.isdelete</code>. 是否删除
     */
    public final TableField<GchUserAttentionCarModelRecord, Integer> ISDELETE = createField("isdelete", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "是否删除");

    /**
     * The column <code>gouchehui2.0.gch_user_attention_car_model.updatetime</code>. 修改时间
     */
    public final TableField<GchUserAttentionCarModelRecord, Timestamp> UPDATETIME = createField("updatetime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0000-00-00 00:00:00", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "修改时间");

    /**
     * The column <code>gouchehui2.0.gch_user_attention_car_model.updateuser</code>. 修改人
     */
    public final TableField<GchUserAttentionCarModelRecord, String> UPDATEUSER = createField("updateuser", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "修改人");

    /**
     * Create a <code>gouchehui2.0.gch_user_attention_car_model</code> table reference
     */
    public GchUserAttentionCarModel() {
        this("gch_user_attention_car_model", null);
    }

    /**
     * Create an aliased <code>gouchehui2.0.gch_user_attention_car_model</code> table reference
     */
    public GchUserAttentionCarModel(String alias) {
        this(alias, GCH_USER_ATTENTION_CAR_MODEL);
    }

    private GchUserAttentionCarModel(String alias, Table<GchUserAttentionCarModelRecord> aliased) {
        this(alias, aliased, null);
    }

    private GchUserAttentionCarModel(String alias, Table<GchUserAttentionCarModelRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "用户关注车型表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Gouchehui2_0.GOUCHEHUI2_0;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GchUserAttentionCarModelRecord> getPrimaryKey() {
        return Keys.KEY_GCH_USER_ATTENTION_CAR_MODEL_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GchUserAttentionCarModelRecord>> getKeys() {
        return Arrays.<UniqueKey<GchUserAttentionCarModelRecord>>asList(Keys.KEY_GCH_USER_ATTENTION_CAR_MODEL_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchUserAttentionCarModel as(String alias) {
        return new GchUserAttentionCarModel(alias, this);
    }

    /**
     * Rename this table
     */
    public GchUserAttentionCarModel rename(String name) {
        return new GchUserAttentionCarModel(name, null);
    }
}
