/**
 * This class is generated by jOOQ
 */
package com.lrest.server.jooqmodel.tables;


import com.lrest.server.jooqmodel.Gouchehui2_0;
import com.lrest.server.jooqmodel.Keys;
import com.lrest.server.jooqmodel.tables.records.GchUserActivityRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GchUserActivity extends TableImpl<GchUserActivityRecord> {

    private static final long serialVersionUID = 1296080163;

    /**
     * The reference instance of <code>gouchehui2.0.gch_user_activity</code>
     */
    public static final GchUserActivity GCH_USER_ACTIVITY = new GchUserActivity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GchUserActivityRecord> getRecordType() {
        return GchUserActivityRecord.class;
    }

    /**
     * The column <code>gouchehui2.0.gch_user_activity.id</code>. 主键id
     */
    public final TableField<GchUserActivityRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "主键id");

    /**
     * The column <code>gouchehui2.0.gch_user_activity.source</code>. 来源：1：web端，2：微信端
     */
    public final TableField<GchUserActivityRecord, Integer> SOURCE = createField("source", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.INTEGER)), this, "来源：1：web端，2：微信端");

    /**
     * The column <code>gouchehui2.0.gch_user_activity.user_name</code>. 用户名
     */
    public final TableField<GchUserActivityRecord, String> USER_NAME = createField("user_name", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "用户名");

    /**
     * The column <code>gouchehui2.0.gch_user_activity.tel</code>. 手机号
     */
    public final TableField<GchUserActivityRecord, String> TEL = createField("tel", org.jooq.impl.SQLDataType.VARCHAR.length(11), this, "手机号");

    /**
     * The column <code>gouchehui2.0.gch_user_activity.activity_price</code>. 活动价
     */
    public final TableField<GchUserActivityRecord, String> ACTIVITY_PRICE = createField("activity_price", org.jooq.impl.SQLDataType.VARCHAR.length(10), this, "活动价");

    /**
     * The column <code>gouchehui2.0.gch_user_activity.brand_id</code>. 品牌id
     */
    public final TableField<GchUserActivityRecord, String> BRAND_ID = createField("brand_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "品牌id");

    /**
     * The column <code>gouchehui2.0.gch_user_activity.brand_name</code>. 品牌名称
     */
    public final TableField<GchUserActivityRecord, String> BRAND_NAME = createField("brand_name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "品牌名称");

    /**
     * The column <code>gouchehui2.0.gch_user_activity.car_model_id</code>. 车型id
     */
    public final TableField<GchUserActivityRecord, String> CAR_MODEL_ID = createField("car_model_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "车型id");

    /**
     * The column <code>gouchehui2.0.gch_user_activity.car_model_name</code>. 车型名称
     */
    public final TableField<GchUserActivityRecord, String> CAR_MODEL_NAME = createField("car_model_name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "车型名称");

    /**
     * The column <code>gouchehui2.0.gch_user_activity.car_id</code>. 车款id
     */
    public final TableField<GchUserActivityRecord, String> CAR_ID = createField("car_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "车款id");

    /**
     * The column <code>gouchehui2.0.gch_user_activity.car_name</code>. 车款名称
     */
    public final TableField<GchUserActivityRecord, String> CAR_NAME = createField("car_name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "车款名称");

    /**
     * The column <code>gouchehui2.0.gch_user_activity.exterior_color_id</code>. 外观颜色id
     */
    public final TableField<GchUserActivityRecord, String> EXTERIOR_COLOR_ID = createField("exterior_color_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "外观颜色id");

    /**
     * The column <code>gouchehui2.0.gch_user_activity.exterior_color_name</code>. 外观颜色名称
     */
    public final TableField<GchUserActivityRecord, String> EXTERIOR_COLOR_NAME = createField("exterior_color_name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "外观颜色名称");

    /**
     * The column <code>gouchehui2.0.gch_user_activity.interior_color_id</code>. 内饰颜色id
     */
    public final TableField<GchUserActivityRecord, String> INTERIOR_COLOR_ID = createField("interior_color_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "内饰颜色id");

    /**
     * The column <code>gouchehui2.0.gch_user_activity.interior_color_name</code>. 内饰颜色名称
     */
    public final TableField<GchUserActivityRecord, String> INTERIOR_COLOR_NAME = createField("interior_color_name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "内饰颜色名称");

    /**
     * The column <code>gouchehui2.0.gch_user_activity.activity_number</code>. 活动编号
     */
    public final TableField<GchUserActivityRecord, String> ACTIVITY_NUMBER = createField("activity_number", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "活动编号");

    /**
     * The column <code>gouchehui2.0.gch_user_activity.activity_name</code>. 活动名称
     */
    public final TableField<GchUserActivityRecord, String> ACTIVITY_NAME = createField("activity_name", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "活动名称");

    /**
     * The column <code>gouchehui2.0.gch_user_activity.flag</code>. 活动类型：1：立即报名，2：特价车，3：立即购买，4：马上抢
     */
    public final TableField<GchUserActivityRecord, Integer> FLAG = createField("flag", org.jooq.impl.SQLDataType.INTEGER, this, "活动类型：1：立即报名，2：特价车，3：立即购买，4：马上抢");

    /**
     * The column <code>gouchehui2.0.gch_user_activity.createtime</code>. 创建时间
     */
    public final TableField<GchUserActivityRecord, Timestamp> CREATETIME = createField("createtime", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");

    /**
     * The column <code>gouchehui2.0.gch_user_activity.createuser</code>. 创建人
     */
    public final TableField<GchUserActivityRecord, String> CREATEUSER = createField("createuser", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "创建人");

    /**
     * The column <code>gouchehui2.0.gch_user_activity.isdelete</code>. 是否删除
     */
    public final TableField<GchUserActivityRecord, Integer> ISDELETE = createField("isdelete", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "是否删除");

    /**
     * The column <code>gouchehui2.0.gch_user_activity.updatetime</code>. 修改时间
     */
    public final TableField<GchUserActivityRecord, Timestamp> UPDATETIME = createField("updatetime", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.inline("0000-00-00 00:00:00", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "修改时间");

    /**
     * The column <code>gouchehui2.0.gch_user_activity.updateuser</code>. 修改人
     */
    public final TableField<GchUserActivityRecord, String> UPDATEUSER = createField("updateuser", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "修改人");

    /**
     * The column <code>gouchehui2.0.gch_user_activity.reward_type</code>. 奖励的标识(积分,优惠券)
     */
    public final TableField<GchUserActivityRecord, String> REWARD_TYPE = createField("reward_type", org.jooq.impl.SQLDataType.VARCHAR.length(10), this, "奖励的标识(积分,优惠券)");

    /**
     * The column <code>gouchehui2.0.gch_user_activity.reward_id</code>. 奖励的唯一标识
     */
    public final TableField<GchUserActivityRecord, String> REWARD_ID = createField("reward_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "奖励的唯一标识");

    /**
     * The column <code>gouchehui2.0.gch_user_activity.remarks</code>. 备注
     */
    public final TableField<GchUserActivityRecord, String> REMARKS = createField("remarks", org.jooq.impl.SQLDataType.VARCHAR.length(512), this, "备注");

    /**
     * The column <code>gouchehui2.0.gch_user_activity.status_track</code>. 询价订单状态（1：未跟踪，2：已跟踪）
     */
    public final TableField<GchUserActivityRecord, Integer> STATUS_TRACK = createField("status_track", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.INTEGER)), this, "询价订单状态（1：未跟踪，2：已跟踪）");

    /**
     * The column <code>gouchehui2.0.gch_user_activity.cus_name</code>. 客户姓名
     */
    public final TableField<GchUserActivityRecord, String> CUS_NAME = createField("cus_name", org.jooq.impl.SQLDataType.VARCHAR.length(32).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "客户姓名");

    /**
     * The column <code>gouchehui2.0.gch_user_activity.cus_remark</code>. 客服备注
     */
    public final TableField<GchUserActivityRecord, String> CUS_REMARK = createField("cus_remark", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "客服备注");

    /**
     * The column <code>gouchehui2.0.gch_user_activity.cus_character</code>. 客服-角色判读（1：用户，2：内部）
     */
    public final TableField<GchUserActivityRecord, String> CUS_CHARACTER = createField("cus_character", org.jooq.impl.SQLDataType.VARCHAR.length(32).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "客服-角色判读（1：用户，2：内部）");

    /**
     * Create a <code>gouchehui2.0.gch_user_activity</code> table reference
     */
    public GchUserActivity() {
        this("gch_user_activity", null);
    }

    /**
     * Create an aliased <code>gouchehui2.0.gch_user_activity</code> table reference
     */
    public GchUserActivity(String alias) {
        this(alias, GCH_USER_ACTIVITY);
    }

    private GchUserActivity(String alias, Table<GchUserActivityRecord> aliased) {
        this(alias, aliased, null);
    }

    private GchUserActivity(String alias, Table<GchUserActivityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Gouchehui2_0.GOUCHEHUI2_0;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GchUserActivityRecord> getPrimaryKey() {
        return Keys.KEY_GCH_USER_ACTIVITY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GchUserActivityRecord>> getKeys() {
        return Arrays.<UniqueKey<GchUserActivityRecord>>asList(Keys.KEY_GCH_USER_ACTIVITY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchUserActivity as(String alias) {
        return new GchUserActivity(alias, this);
    }

    /**
     * Rename this table
     */
    public GchUserActivity rename(String name) {
        return new GchUserActivity(name, null);
    }
}
