/**
 * This class is generated by jOOQ
 */
package com.lrest.server.jooqmodel.tables.records;


import com.lrest.server.jooqmodel.tables.GchViewCarPrice;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GchViewCarPriceRecord extends TableRecordImpl<GchViewCarPriceRecord> {

    private static final long serialVersionUID = -317768247;

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.id</code>. 主键
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.id</code>. 主键
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.exterior_color_id</code>. 外观颜色ID
     */
    public void setExteriorColorId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.exterior_color_id</code>. 外观颜色ID
     */
    public String getExteriorColorId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.interior_color_id</code>. 内饰颜色ID
     */
    public void setInteriorColorId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.interior_color_id</code>. 内饰颜色ID
     */
    public String getInteriorColorId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.user_id</code>. 所属用户
     */
    public void setUserId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.user_id</code>. 所属用户
     */
    public String getUserId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.access_quantity</code>. 访问量
     */
    public void setAccessQuantity(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.access_quantity</code>. 访问量
     */
    public Integer getAccessQuantity() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.transactions_count</code>. 成交量
     */
    public void setTransactionsCount(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.transactions_count</code>. 成交量
     */
    public Integer getTransactionsCount() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.asking_price_count</code>. 询价量
     */
    public void setAskingPriceCount(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.asking_price_count</code>. 询价量
     */
    public Integer getAskingPriceCount() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.price</code>. 指导价
     */
    public void setPrice(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.price</code>. 指导价
     */
    public String getPrice() {
        return (String) get(7);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.discount</code>. 优惠
     */
    public void setDiscount(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.discount</code>. 优惠
     */
    public Integer getDiscount() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.stock</code>. 库存
     */
    public void setStock(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.stock</code>. 库存
     */
    public String getStock() {
        return (String) get(9);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.onway</code>. 在途
     */
    public void setOnway(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.onway</code>. 在途
     */
    public String getOnway() {
        return (String) get(10);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.createtime</code>. 创建时间
     */
    public void setCreatetime(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.createtime</code>. 创建时间
     */
    public Timestamp getCreatetime() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.createuser</code>. 创建人
     */
    public void setCreateuser(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.createuser</code>. 创建人
     */
    public String getCreateuser() {
        return (String) get(12);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.isdelete</code>. 是否删除
     */
    public void setIsdelete(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.isdelete</code>. 是否删除
     */
    public Integer getIsdelete() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.updatetime</code>. 修改时间
     */
    public void setUpdatetime(Timestamp value) {
        set(14, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.updatetime</code>. 修改时间
     */
    public Timestamp getUpdatetime() {
        return (Timestamp) get(14);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.updateuser</code>. 修改人
     */
    public void setUpdateuser(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.updateuser</code>. 修改人
     */
    public String getUpdateuser() {
        return (String) get(15);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.low_price</code>. 报价
     */
    public void setLowPrice(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.low_price</code>. 报价
     */
    public Integer getLowPrice() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.interior_color_name</code>. 名称
     */
    public void setInteriorColorName(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.interior_color_name</code>. 名称
     */
    public String getInteriorColorName() {
        return (String) get(17);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.interior_color_value</code>. 色值
     */
    public void setInteriorColorValue(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.interior_color_value</code>. 色值
     */
    public String getInteriorColorValue() {
        return (String) get(18);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.interior_color_imageurl</code>. 图片
     */
    public void setInteriorColorImageurl(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.interior_color_imageurl</code>. 图片
     */
    public String getInteriorColorImageurl() {
        return (String) get(19);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.exterior_color_name</code>. 名称
     */
    public void setExteriorColorName(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.exterior_color_name</code>. 名称
     */
    public String getExteriorColorName() {
        return (String) get(20);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.exterior_color_value</code>. 色值
     */
    public void setExteriorColorValue(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.exterior_color_value</code>. 色值
     */
    public String getExteriorColorValue() {
        return (String) get(21);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.exterior_color_imgurl</code>. 图片
     */
    public void setExteriorColorImgurl(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.exterior_color_imgurl</code>. 图片
     */
    public String getExteriorColorImgurl() {
        return (String) get(22);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.car_id</code>.
     */
    public void setCarId(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.car_id</code>.
     */
    public String getCarId() {
        return (String) get(23);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.car_name</code>. 名称
     */
    public void setCarName(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.car_name</code>. 名称
     */
    public String getCarName() {
        return (String) get(24);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.car_model_id</code>. 所属车型
     */
    public void setCarModelId(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.car_model_id</code>. 所属车型
     */
    public String getCarModelId() {
        return (String) get(25);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.car_model_name</code>. 名称
     */
    public void setCarModelName(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.car_model_name</code>. 名称
     */
    public String getCarModelName() {
        return (String) get(26);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.car_type_id</code>. 所属分类
     */
    public void setCarTypeId(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.car_type_id</code>. 所属分类
     */
    public String getCarTypeId() {
        return (String) get(27);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.car_type_name</code>. 名称
     */
    public void setCarTypeName(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.car_type_name</code>. 名称
     */
    public String getCarTypeName() {
        return (String) get(28);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.car_model_imageurl</code>. 图片
     */
    public void setCarModelImageurl(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.car_model_imageurl</code>. 图片
     */
    public String getCarModelImageurl() {
        return (String) get(29);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.brand_id</code>. 所属品牌
     */
    public void setBrandId(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.brand_id</code>. 所属品牌
     */
    public String getBrandId() {
        return (String) get(30);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.brand_name</code>. 名称
     */
    public void setBrandName(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.brand_name</code>. 名称
     */
    public String getBrandName() {
        return (String) get(31);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.alif</code>.
     */
    public void setAlif(String value) {
        set(32, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.alif</code>.
     */
    public String getAlif() {
        return (String) get(32);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.city_name</code>. 城市名称
     */
    public void setCityName(String value) {
        set(33, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.city_name</code>. 城市名称
     */
    public String getCityName() {
        return (String) get(33);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.province_id</code>. 所属省份
     */
    public void setProvinceId(String value) {
        set(34, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.province_id</code>. 所属省份
     */
    public String getProvinceId() {
        return (String) get(34);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.province_name</code>. 省份名称
     */
    public void setProvinceName(String value) {
        set(35, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.province_name</code>. 省份名称
     */
    public String getProvinceName() {
        return (String) get(35);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.car_xj_count</code>. 询价总数
     */
    public void setCarXjCount(Integer value) {
        set(36, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.car_xj_count</code>. 询价总数
     */
    public Integer getCarXjCount() {
        return (Integer) get(36);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.is_xunjia</code>. 是否需要询价(1需要询价,2不需要询价)
     */
    public void setIsXunjia(Integer value) {
        set(37, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.is_xunjia</code>. 是否需要询价(1需要询价,2不需要询价)
     */
    public Integer getIsXunjia() {
        return (Integer) get(37);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.brand_alif</code>.
     */
    public void setBrandAlif(String value) {
        set(38, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.brand_alif</code>.
     */
    public String getBrandAlif() {
        return (String) get(38);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.model_alif</code>.
     */
    public void setModelAlif(String value) {
        set(39, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.model_alif</code>.
     */
    public String getModelAlif() {
        return (String) get(39);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.car_model_xj_count</code>. 询价次数
     */
    public void setCarModelXjCount(Integer value) {
        set(40, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.car_model_xj_count</code>. 询价次数
     */
    public Integer getCarModelXjCount() {
        return (Integer) get(40);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.show_index</code>. 显示索引
     */
    public void setShowIndex(Integer value) {
        set(41, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.show_index</code>. 显示索引
     */
    public Integer getShowIndex() {
        return (Integer) get(41);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.brand_access_quantity</code>. 访问量
     */
    public void setBrandAccessQuantity(Integer value) {
        set(42, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.brand_access_quantity</code>. 访问量
     */
    public Integer getBrandAccessQuantity() {
        return (Integer) get(42);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.description</code>. 描述
     */
    public void setDescription(String value) {
        set(43, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.description</code>. 描述
     */
    public String getDescription() {
        return (String) get(43);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.car_status</code>. 车款状态 1：在售；0：停售。
     */
    public void setCarStatus(Byte value) {
        set(44, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.car_status</code>. 车款状态 1：在售；0：停售。
     */
    public Byte getCarStatus() {
        return (Byte) get(44);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.name_4s</code>. 4S店名称
     */
    public void setName_4s(String value) {
        set(45, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.name_4s</code>. 4S店名称
     */
    public String getName_4s() {
        return (String) get(45);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.brand_4s</code>. 4S店主营品牌
     */
    public void setBrand_4s(String value) {
        set(46, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.brand_4s</code>. 4S店主营品牌
     */
    public String getBrand_4s() {
        return (String) get(46);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.addr</code>. 地址
     */
    public void setAddr(String value) {
        set(47, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.addr</code>. 地址
     */
    public String getAddr() {
        return (String) get(47);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.city_id</code>. 城市ID
     */
    public void setCityId(String value) {
        set(48, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.city_id</code>. 城市ID
     */
    public String getCityId() {
        return (String) get(48);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.auth_price</code>. 官方指导价
     */
    public void setAuthPrice(Integer value) {
        set(49, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.auth_price</code>. 官方指导价
     */
    public Integer getAuthPrice() {
        return (Integer) get(49);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.exterior_img</code>. 图片
     */
    public void setExteriorImg(String value) {
        set(50, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.exterior_img</code>. 图片
     */
    public String getExteriorImg() {
        return (String) get(50);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.displacement</code>. 排量
     */
    public void setDisplacement(String value) {
        set(51, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.displacement</code>. 排量
     */
    public String getDisplacement() {
        return (String) get(51);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.logo</code>. logo
     */
    public void setLogo(String value) {
        set(52, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.logo</code>. logo
     */
    public String getLogo() {
        return (String) get(52);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_view_car_price.model_access_quantity</code>. 访问量
     */
    public void setModelAccessQuantity(Integer value) {
        set(53, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_view_car_price.model_access_quantity</code>. 访问量
     */
    public Integer getModelAccessQuantity() {
        return (Integer) get(53);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GchViewCarPriceRecord
     */
    public GchViewCarPriceRecord() {
        super(GchViewCarPrice.GCH_VIEW_CAR_PRICE);
    }

    /**
     * Create a detached, initialised GchViewCarPriceRecord
     */
    public GchViewCarPriceRecord(String id, String exteriorColorId, String interiorColorId, String userId, Integer accessQuantity, Integer transactionsCount, Integer askingPriceCount, String price, Integer discount, String stock, String onway, Timestamp createtime, String createuser, Integer isdelete, Timestamp updatetime, String updateuser, Integer lowPrice, String interiorColorName, String interiorColorValue, String interiorColorImageurl, String exteriorColorName, String exteriorColorValue, String exteriorColorImgurl, String carId, String carName, String carModelId, String carModelName, String carTypeId, String carTypeName, String carModelImageurl, String brandId, String brandName, String alif, String cityName, String provinceId, String provinceName, Integer carXjCount, Integer isXunjia, String brandAlif, String modelAlif, Integer carModelXjCount, Integer showIndex, Integer brandAccessQuantity, String description, Byte carStatus, String name_4s, String brand_4s, String addr, String cityId, Integer authPrice, String exteriorImg, String displacement, String logo, Integer modelAccessQuantity) {
        super(GchViewCarPrice.GCH_VIEW_CAR_PRICE);

        set(0, id);
        set(1, exteriorColorId);
        set(2, interiorColorId);
        set(3, userId);
        set(4, accessQuantity);
        set(5, transactionsCount);
        set(6, askingPriceCount);
        set(7, price);
        set(8, discount);
        set(9, stock);
        set(10, onway);
        set(11, createtime);
        set(12, createuser);
        set(13, isdelete);
        set(14, updatetime);
        set(15, updateuser);
        set(16, lowPrice);
        set(17, interiorColorName);
        set(18, interiorColorValue);
        set(19, interiorColorImageurl);
        set(20, exteriorColorName);
        set(21, exteriorColorValue);
        set(22, exteriorColorImgurl);
        set(23, carId);
        set(24, carName);
        set(25, carModelId);
        set(26, carModelName);
        set(27, carTypeId);
        set(28, carTypeName);
        set(29, carModelImageurl);
        set(30, brandId);
        set(31, brandName);
        set(32, alif);
        set(33, cityName);
        set(34, provinceId);
        set(35, provinceName);
        set(36, carXjCount);
        set(37, isXunjia);
        set(38, brandAlif);
        set(39, modelAlif);
        set(40, carModelXjCount);
        set(41, showIndex);
        set(42, brandAccessQuantity);
        set(43, description);
        set(44, carStatus);
        set(45, name_4s);
        set(46, brand_4s);
        set(47, addr);
        set(48, cityId);
        set(49, authPrice);
        set(50, exteriorImg);
        set(51, displacement);
        set(52, logo);
        set(53, modelAccessQuantity);
    }
}
