/**
 * This class is generated by jOOQ
 */
package com.lrest.server.jooqmodel.tables.records;


import com.lrest.server.jooqmodel.tables.GchWxpayPackage;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GchWxpayPackageRecord extends UpdatableRecordImpl<GchWxpayPackageRecord> implements Record9<Integer, String, String, String, Integer, String, String, String, String> {

    private static final long serialVersionUID = -1890389974;

    /**
     * Setter for <code>gouchehui2.0.gch_wxpay_package.id</code>. 主键ID
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_wxpay_package.id</code>. 主键ID
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_wxpay_package.pay_id</code>.
     */
    public void setPayId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_wxpay_package.pay_id</code>.
     */
    public String getPayId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_wxpay_package.out_trade_no</code>. 本系统的订单号
     */
    public void setOutTradeNo(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_wxpay_package.out_trade_no</code>. 本系统的订单号
     */
    public String getOutTradeNo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_wxpay_package.transaction_id</code>. 微信支付订单号
     */
    public void setTransactionId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_wxpay_package.transaction_id</code>. 微信支付订单号
     */
    public String getTransactionId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_wxpay_package.total_fee</code>. 订单总金额(单位为分)
     */
    public void setTotalFee(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_wxpay_package.total_fee</code>. 订单总金额(单位为分)
     */
    public Integer getTotalFee() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_wxpay_package.trade_type</code>. 交易类型
     */
    public void setTradeType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_wxpay_package.trade_type</code>. 交易类型
     */
    public String getTradeType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_wxpay_package.bank_type</code>. 付款银行
     */
    public void setBankType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_wxpay_package.bank_type</code>. 付款银行
     */
    public String getBankType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_wxpay_package.time_end</code>.
     */
    public void setTimeEnd(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_wxpay_package.time_end</code>.
     */
    public String getTimeEnd() {
        return (String) get(7);
    }

    /**
     * Setter for <code>gouchehui2.0.gch_wxpay_package.package</code>. 整个返回包
     */
    public void setPackage(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>gouchehui2.0.gch_wxpay_package.package</code>. 整个返回包
     */
    public String getPackage() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, Integer, String, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, Integer, String, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return GchWxpayPackage.GCH_WXPAY_PACKAGE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return GchWxpayPackage.GCH_WXPAY_PACKAGE.PAY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return GchWxpayPackage.GCH_WXPAY_PACKAGE.OUT_TRADE_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return GchWxpayPackage.GCH_WXPAY_PACKAGE.TRANSACTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return GchWxpayPackage.GCH_WXPAY_PACKAGE.TOTAL_FEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return GchWxpayPackage.GCH_WXPAY_PACKAGE.TRADE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return GchWxpayPackage.GCH_WXPAY_PACKAGE.BANK_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return GchWxpayPackage.GCH_WXPAY_PACKAGE.TIME_END;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return GchWxpayPackage.GCH_WXPAY_PACKAGE.PACKAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPayId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOutTradeNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTransactionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getTotalFee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getTradeType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getBankType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getTimeEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getPackage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchWxpayPackageRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchWxpayPackageRecord value2(String value) {
        setPayId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchWxpayPackageRecord value3(String value) {
        setOutTradeNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchWxpayPackageRecord value4(String value) {
        setTransactionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchWxpayPackageRecord value5(Integer value) {
        setTotalFee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchWxpayPackageRecord value6(String value) {
        setTradeType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchWxpayPackageRecord value7(String value) {
        setBankType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchWxpayPackageRecord value8(String value) {
        setTimeEnd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchWxpayPackageRecord value9(String value) {
        setPackage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GchWxpayPackageRecord values(Integer value1, String value2, String value3, String value4, Integer value5, String value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GchWxpayPackageRecord
     */
    public GchWxpayPackageRecord() {
        super(GchWxpayPackage.GCH_WXPAY_PACKAGE);
    }

    /**
     * Create a detached, initialised GchWxpayPackageRecord
     */
    public GchWxpayPackageRecord(Integer id, String payId, String outTradeNo, String transactionId, Integer totalFee, String tradeType, String bankType, String timeEnd, String package_) {
        super(GchWxpayPackage.GCH_WXPAY_PACKAGE);

        set(0, id);
        set(1, payId);
        set(2, outTradeNo);
        set(3, transactionId);
        set(4, totalFee);
        set(5, tradeType);
        set(6, bankType);
        set(7, timeEnd);
        set(8, package_);
    }
}
