/**
 * This class is generated by jOOQ
 */
package com.lrest.server.jooqmodel;


import com.lrest.server.jooqmodel.tables.GchCar;
import com.lrest.server.jooqmodel.tables.GchPay;
import com.lrest.server.jooqmodel.tables.GchPayAreaLowPrice;
import com.lrest.server.jooqmodel.tables.GchViewCarPrice;
import com.lrest.server.jooqmodel.tables.GchWxpayPackage;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Gouchehui2_0 extends SchemaImpl {

    private static final long serialVersionUID = -1396020300;

    /**
     * The reference instance of <code>gouchehui2.0</code>
     */
    public static final Gouchehui2_0 GOUCHEHUI2_0 = new Gouchehui2_0();

    /**
     * 车款表
     */
    public final GchCar GCH_CAR = com.lrest.server.jooqmodel.tables.GchCar.GCH_CAR;

    /**
     * 询价定车支付表
     */
    public final GchPay GCH_PAY = com.lrest.server.jooqmodel.tables.GchPay.GCH_PAY;

    /**
     * 订单中区域最低价表
     */
    public final GchPayAreaLowPrice GCH_PAY_AREA_LOW_PRICE = com.lrest.server.jooqmodel.tables.GchPayAreaLowPrice.GCH_PAY_AREA_LOW_PRICE;

    /**
     * VIEW
     */
    public final GchViewCarPrice GCH_VIEW_CAR_PRICE = com.lrest.server.jooqmodel.tables.GchViewCarPrice.GCH_VIEW_CAR_PRICE;

    /**
     * The table <code>gouchehui2.0.gch_wxpay_package</code>.
     */
    public final GchWxpayPackage GCH_WXPAY_PACKAGE = com.lrest.server.jooqmodel.tables.GchWxpayPackage.GCH_WXPAY_PACKAGE;

    /**
     * No further instances allowed
     */
    private Gouchehui2_0() {
        super("gouchehui2.0", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            GchCar.GCH_CAR,
            GchPay.GCH_PAY,
            GchPayAreaLowPrice.GCH_PAY_AREA_LOW_PRICE,
            GchViewCarPrice.GCH_VIEW_CAR_PRICE,
            GchWxpayPackage.GCH_WXPAY_PACKAGE);
    }
}
